import type { RouteDefinition } from './types';

export const borneoMphRoute: RouteDefinition = {
  id: 'borneo-mph',
  title: 'Borneo Atrium → MPH',
  fromNode: 'Borneo Atrium',
  toNode: 'MPH',
  scenes: [
            {
                id: 1,
                image: '/images360/L-B-18.jpg',
                label: 'You arrive the Borneo Atrium! Welcome!',
                initialYaw: 180,
                forward: { yaw: 190, pitch: -7 },
            },
            {
                id: 2,
                image: '/images360/L-B-16.jpg',
                label: 'Left side got escalator can go up to Junction',
                initialYaw: 175,
                back : { yaw: 10, pitch: 0 },
                forward : { yaw: 180, pitch: -5 },
            },
            {
                id: 3,
                image: '/images360/L-B-15.jpg',
                label: 'You are almost there',
                initialYaw: 175,
                back : { yaw: 355, pitch: 0 },
                forward : { yaw: 213, pitch: -6 },
            },
            {
                id: 4,
                image: '/images360/L-B-12.jpg',
                label: 'Leisure Zone',
                initialYaw: 250,
                back : { yaw: 355, pitch: 0 },
                forward : { yaw: 250, pitch: -5 },
            },
            {
                id: 5,
                image: '/images360/L-B-10.jpg',
                label: 'Go Straight and ready turn left',
                initialYaw: 360,
                back : { yaw: 165, pitch: -4 },
                forward : { yaw: 358, pitch: 0 },
            },
            {
                id: 6,
                image: '/images360/L-B-8.jpg',
                label: 'Walkway in Corridor',
                initialYaw: 180,
                back : { yaw: 355, pitch: 0 },
                forward : { yaw: 175, pitch: -4 },
            },
            {
                id: 7,
                image: '/images360/L-B-6.jpg',
                label: 'Walkway in Corridor',
                initialYaw: 90,
                back : { yaw: 355, pitch: 0 },
                forward : { yaw: 89, pitch: -4 },
            },
            {
                id: 8,
                image: '/images360/L-B-3.jpg',
                label: 'Block A Groundfloor Toilet',
                initialYaw: 60,
                back : { yaw: 178, pitch: -5 },
                forward : { yaw: 70, pitch: -6 },
            },
            {
                id: 9,
                image: '/images360/L-B-1.jpg',
                label: 'Block A Lobby',
                initialYaw: 200,
                forward: { yaw: 190, pitch: -3 },
                back : { yaw: 30, pitch: 0 },
            },
            {
                id: 10,
                image: '/images360/lobby2.jpg',
                label: 'Outside Block A Lobby',
                initialYaw: 30,
                forward: { yaw: 50, pitch: 0 },
                back: { yaw: 180, pitch: 0 },
            },
            {
                id: 11,
                image: '/images360/L-M-7.jpg',
                label: 'Towards MPH',
                initialYaw: 250,
                forward: { yaw: 235, pitch: 0 },
                back: { yaw: 90, pitch: 0 },
            },
            {
                id: 12,
                image: '/images360/L-M-10.jpg',
                label: 'Go Straight',
                initialYaw: 0,
                forward: { yaw: 353, pitch: 0 },
                back: { yaw: 190, pitch: -4 },
            },
            {
                id: 13,
                image: '/images360/L-M-13.jpg',
                label: 'Ready to turn right into MPH',
                initialYaw: 360,
                forward: { yaw: 360, pitch: 0 },
                back: { yaw: 175, pitch: -5 },
            },
            {
                id: 14,
                image: '/images360/L-M-16.jpg',
                label: 'Enter the MPH Door',
                initialYaw: 360,
                forward: { yaw: 360, pitch: 0 },
                back: { yaw: 87, pitch: -5 },
            },
            {
                id: 15,
                image: '/images360/L-M-17.jpg',
                label: 'Multi Purpose Hall Lobby',
                initialYaw: 345,
                forward: { yaw: 340, pitch: 0 },
                back: { yaw: 165, pitch: -4 },
            },
            {
                id: 16,
                image: '/images360/L-M-18.jpg',
                label: 'You arrived at the MPH! Welcome!',
                initialYaw: 0,
            },
  ],
};

export const borneoHqRoute: RouteDefinition = {
  id: 'borneo-hq',
  title: 'Borneo Atrium → HQ',
  fromNode: 'Borneo Atrium',
  toNode: 'HQ',
  scenes: [
    {
      id: 1,
      image: '/images360/L-B-18.jpg',
      label: 'You arrive the Borneo Atrium! Welcome!',
      initialYaw: 180,
      forward: { yaw: 190, pitch: -7 },
    },
    {
      id: 2,
      image: '/images360/L-B-16.jpg',
      label: 'Left side got escalator can go up to Junction',
      initialYaw: 175,
      back: { yaw: 10, pitch: 0 },
      forward: { yaw: 180, pitch: -5 },
    },
    {
      id: 3,
      image: '/images360/L-B-15.jpg',
      label: 'You are almost there',
      initialYaw: 175,
      back: { yaw: 355, pitch: 0 },
      forward: { yaw: 213, pitch: -6 },
    },
    {
      id: 4,
      image: '/images360/L-B-12.jpg',
      label: 'Leisure Zone',
      initialYaw: 250,
      back: { yaw: 355, pitch: 0 },
      forward: { yaw: 250, pitch: -5 },
    },
    {
      id: 5,
      image: '/images360/L-B-10.jpg',
      label: 'Go Straight and ready turn left',
      initialYaw: 360,
      back: { yaw: 165, pitch: -4 },
      forward: { yaw: 358, pitch: 0 },
    },
    {
      id: 6,
      image: '/images360/L-B-8.jpg',
      label: 'Walkway in Corridor',
      initialYaw: 180,
      back: { yaw: 355, pitch: 0 },
      forward: { yaw: 175, pitch: -4 },
    },
    {
      id: 7,
      image: '/images360/L-B-6.jpg',
      label: 'Walkway in Corridor',
      initialYaw: 90,
      back: { yaw: 355, pitch: 0 },
      forward: { yaw: 89, pitch: -4 },
    },
    {
      id: 8,
      image: '/images360/L-B-3.jpg',
      label: 'Block A Groundfloor Toilet',
      initialYaw: 60,
      back: { yaw: 178, pitch: -5 },
      forward: { yaw: 40, pitch: -6 },
    },
    {
      id: 9,
      image: '/images360/L-H-2.jpg',
      label: 'Student HQ Entrance',
      initialYaw: 0,
      forward: { yaw: 350, pitch: 0 },
      back: { yaw: 140, pitch: 0 },
    },
    {
      id: 10,
      image: '/images360/L-H-3.jpg',
      label: 'Financial Desk Services Area',
      initialYaw: 18,
      forward: { yaw: 55, pitch: 0 },
      back: { yaw: 160, pitch: 0 },
    },
    {
      id: 11,
      image: '/images360/L-H-4.jpg',
      label: 'Student HQ Lobby',
      initialYaw: 330,
    },
  ],
};

export const borneoShubRoute: RouteDefinition = {
  id: 'borneo-shub',
  title: 'Borneo Atrium → Student Hub',
  fromNode: 'Borneo Atrium',
  toNode: 'Student Hub',
  scenes: [
            {
                id: 1,
                image: '/images360/L-B-18.jpg',
                label: 'You arrive the Borneo Atrium! Welcome!',
                initialYaw: 180,
                forward: { yaw: 190, pitch: -7 },
            },
            {
                id: 2,
                image: '/images360/L-B-16.jpg',
                label: 'Left side got escalator can go up to Junction',
                initialYaw: 175,
                back : { yaw: 10, pitch: 0 },
                forward : { yaw: 180, pitch: -5 },
            },
            {
                id: 3,
                image: '/images360/L-B-15.jpg',
                label: 'You are almost there',
                initialYaw: 175,
                back : { yaw: 355, pitch: 0 },
                forward : { yaw: 213, pitch: -6 },
            },
            {
                id: 5,
                image: '/images360/L-B-12.jpg',
                label: 'Vending Machine Area',
                initialYaw: 250,
                back : { yaw: 355, pitch: 0 },
                forward : { yaw: 250, pitch: -5 },
            },
            {
                id: 6,
                image: '/images360/L-B-10.jpg',
                label: 'Go Straight',
                initialYaw: 360,
                back : { yaw: 165, pitch: -4 },
                forward : { yaw: 358, pitch: 0 },
            },
            {
                id: 7,
                image: '/images360/L-B-8.jpg',
                label: 'Walkway in Corridor',
                initialYaw: 180,
                back : { yaw: 355, pitch: 0 },
                forward : { yaw: 175, pitch: -4 },
            },
            {
                id: 8,
                image: '/images360/L-B-6.jpg',
                label: 'Walkway in Corridor',
                initialYaw: 90,
                back : { yaw: 355, pitch: 0 },
                forward : { yaw: 89, pitch: -4 },
            },
            {
                id: 9,
                image: '/images360/L-B-3.jpg',
                label: 'Block A Groundfloor Toilet',
                initialYaw: 60,
                back : { yaw: 178, pitch: -5 },
                forward : { yaw: 70, pitch: -6 },
            },
            {
              id: 10,
              image: '/images360/LobbyA_3_Dining.jpg',
              label: 'Lobby A → G Block Corridor Entrance',
              initialYaw: 0,
              forward: { yaw: 0, pitch: 0 },
              back: { yaw: 180, pitch: 0 },
            },
            {
              id: 11,
              image: '/images360/LobbyA_5_Dining.jpg',
              label: 'Connecting Corridor',
              initialYaw: 0,
              forward: { yaw: 0, pitch: 0 },
              back: { yaw: 180, pitch: 0 },
            },
            {
              id: 12,
              image: '/images360/LobbyA_6_Dining.jpg',
              label: 'Corridor Midpoint',
              initialYaw: 190,
              forward: { yaw: 185, pitch: 0 },
              back: { yaw: 359, pitch: 0 },
            },
            {
              id: 13,
              image: '/images360/LobbyA_7_Dining.jpg',
              label: 'G Block Entrance Ahead',
              initialYaw: 220,
              forward: { yaw: 220, pitch: 0 },
              back: { yaw: 0, pitch: 0 },
            },
            {
              id: 14,
              image: '/images360/LobbyA_10_Dining.jpg',
              label: 'G Block Entrance Door',
              initialYaw: 0,
              forward: { yaw: 0, pitch: 0 },
              back: { yaw: 180, pitch: 0 },
            },
            {
              id: 15,
              image: '/images360/LobbyA_11_Dining.jpg',
              label: 'Inside G Block Lobby',
              initialYaw: 0,
              forward: { yaw: 0, pitch: -3 },
              back: { yaw: 180, pitch: -4 },
            },
            {
              id: 16,
              image: '/images360/LobbyA_12_Dining.jpg',
              label: 'Walkway Toward Dining Area',
              initialYaw: 0,
              forward: { yaw: 0, pitch: 0 },
              back: { yaw: 180, pitch: 0 },
            },
            {
              id: 17,
              image: '/images360/LobbyA_13_Dining.jpg',
              label: 'Dining Area First Section',
              initialYaw: 0,
              forward: { yaw: 0, pitch: -3 },
              back: { yaw: 180, pitch: 0 },
            },
            {
              id: 18,
              image: '/images360/LobbyA_17_Dining.jpg',
              label: 'Dining Area Mid Section',
              initialYaw: 0,
              forward: { yaw: 0, pitch: 0 },
              back: { yaw: 180, pitch: 0 },
            },
            {
              id: 19,
              image: '/images360/LobbyA_14_Dining.jpg',
              label: 'Dining Area',
              initialYaw: 0,
              forward: { yaw: 0, pitch: 0 },
              back: { yaw: 185, pitch: -7 },
            },
            {
              id: 20,
              image: '/images360/LobbyA_15_Dining.jpg',
              label: 'Student Hub Entrance Area',
              initialYaw: 15,
              forward: { yaw: 15, pitch: -3 },
              back: { yaw: 185, pitch: -7 },
            },
            {
              id: 21,
              image: '/images360/LobbyA_16_Dining.jpg',
              label: 'Inside Student Hub',
              initialYaw: 0,
              forward: { yaw: 0, pitch: -3 },
              back: { yaw: 176, pitch: -6 },
            },
            {
              id: 22,
              image: '/images360/StudentHub1.jpg',
              label: 'Inside Student Hub',
              initialYaw: 0,
            }, 
  ],
};

export const borneoGblockRoute: RouteDefinition = {
  id: 'borneo-gblock',
  title: 'Borneo Atrium → G Block',
  fromNode: 'Borneo Atrium',
  toNode: 'G Block',
  scenes: [
            {
                id: 1,
                image: '/images360/L-B-18.jpg',
                label: 'You arrive the Borneo Atrium! Welcome!',
                initialYaw: 180,
                forward: { yaw: 190, pitch: -7 },
            },
            {
                id: 2,
                image: '/images360/L-B-16.jpg',
                label: 'Left side got escalator can go up to Junction',
                initialYaw: 175,
                back : { yaw: 10, pitch: 0 },
                forward : { yaw: 180, pitch: -5 },
            },
            {
                id: 3,
                image: '/images360/L-B-15.jpg',
                label: 'You are almost there',
                initialYaw: 175,
                back : { yaw: 355, pitch: 0 },
                forward : { yaw: 213, pitch: -6 },
            },
            {
                id: 5,
                image: '/images360/L-B-12.jpg',
                label: 'Vending Machine Area',
                initialYaw: 250,
                back : { yaw: 355, pitch: 0 },
                forward : { yaw: 250, pitch: -5 },
            },
            {
                id: 6,
                image: '/images360/L-B-10.jpg',
                label: 'Go Straight',
                initialYaw: 360,
                back : { yaw: 165, pitch: -4 },
                forward : { yaw: 358, pitch: 0 },
            },
            {
                id: 7,
                image: '/images360/L-B-8.jpg',
                label: 'Walkway in Corridor',
                initialYaw: 180,
                back : { yaw: 355, pitch: 0 },
                forward : { yaw: 175, pitch: -4 },
            },
            {
                id: 8,
                image: '/images360/L-B-6.jpg',
                label: 'Walkway in Corridor',
                initialYaw: 90,
                back : { yaw: 355, pitch: 0 },
                forward : { yaw: 89, pitch: -4 },
            },
            {
                id: 9,
                image: '/images360/L-B-3.jpg',
                label: 'Block A Groundfloor Toilet',
                initialYaw: 60,
                back : { yaw: 178, pitch: -5 },
                forward : { yaw: 70, pitch: -6 },
            },
            {
              id: 10,
              image: '/images360/LobbyA_3_Dining.jpg',
              label: 'Lobby A → G Block Corridor Entrance',
              initialYaw: 0,
              forward: { yaw: 0, pitch: 0 },
              back: { yaw: 180, pitch: 0 },
            },
            {
              id: 11,
              image: '/images360/LobbyA_5_Dining.jpg',
              label: 'Connecting Corridor',
              initialYaw: 0,
              forward: { yaw: 0, pitch: 0 },
              back: { yaw: 180, pitch: 0 },
            },
            {
              id: 12,
              image: '/images360/LobbyA_6_Dining.jpg',
              label: 'Corridor Midpoint',
              initialYaw: 190,
              forward: { yaw: 185, pitch: 0 },
              back: { yaw: 359, pitch: 0 },
            },
            {
              id: 13,
              image: '/images360/LobbyA_7_Dining.jpg',
              label: 'G Block Entrance Ahead',
              initialYaw: 220,
              forward: { yaw: 220, pitch: 0 },
              back: { yaw: 0, pitch: 0 },
            },
            {
              id: 14,
              image: '/images360/LobbyA_10_Dining.jpg',
              label: 'G Block Entrance Door',
              initialYaw: 0,
              forward: { yaw: 0, pitch: 0 },
              back: { yaw: 180, pitch: 0 },
            },
            {
              id: 15,
              image: '/images360/LobbyA_11_Dining.jpg',
              label: 'Inside G Block Lobby',
              initialYaw: 320,
            },
  ],
};

export const borneoDiningRoute: RouteDefinition = {
  id: 'borneo-dining',
  title: 'Borneo Atrium → Dining Hall',
  fromNode: 'Borneo Atrium',
  toNode: 'Dining Hall',
  scenes: [
            {
                id: 1,
                image: '/images360/L-B-18.jpg',
                label: 'You arrive the Borneo Atrium! Welcome!',
                initialYaw: 180,
                forward: { yaw: 190, pitch: -7 },
            },
            {
                id: 2,
                image: '/images360/L-B-16.jpg',
                label: 'Left side got escalator can go up to Junction',
                initialYaw: 175,
                back : { yaw: 10, pitch: 0 },
                forward : { yaw: 180, pitch: -5 },
            },
            {
                id: 3,
                image: '/images360/L-B-15.jpg',
                label: 'You are almost there',
                initialYaw: 175,
                back : { yaw: 355, pitch: 0 },
                forward : { yaw: 213, pitch: -6 },
            },
            {
                id: 5,
                image: '/images360/L-B-12.jpg',
                label: 'Vending Machine Area',
                initialYaw: 250,
                back : { yaw: 355, pitch: 0 },
                forward : { yaw: 250, pitch: -5 },
            },
            {
                id: 6,
                image: '/images360/L-B-10.jpg',
                label: 'Go Straight',
                initialYaw: 360,
                back : { yaw: 165, pitch: -4 },
                forward : { yaw: 358, pitch: 0 },
            },
            {
                id: 7,
                image: '/images360/L-B-8.jpg',
                label: 'Walkway in Corridor',
                initialYaw: 180,
                back : { yaw: 355, pitch: 0 },
                forward : { yaw: 175, pitch: -4 },
            },
            {
                id: 8,
                image: '/images360/L-B-6.jpg',
                label: 'Walkway in Corridor',
                initialYaw: 90,
                back : { yaw: 355, pitch: 0 },
                forward : { yaw: 89, pitch: -4 },
            },
            {
                id: 9,
                image: '/images360/L-B-3.jpg',
                label: 'Block A Groundfloor Toilet',
                initialYaw: 60,
                back : { yaw: 178, pitch: -5 },
                forward : { yaw: 70, pitch: -6 },
            },
            {
              id: 10,
              image: '/images360/LobbyA_3_Dining.jpg',
              label: 'Lobby A → G Block Corridor Entrance',
              initialYaw: 0,
              forward: { yaw: 0, pitch: 0 },
              back: { yaw: 180, pitch: 0 },
            },
            {
              id: 11,
              image: '/images360/LobbyA_5_Dining.jpg',
              label: 'Connecting Corridor',
              initialYaw: 0,
              forward: { yaw: 0, pitch: 0 },
              back: { yaw: 180, pitch: 0 },
            },
            {
              id: 12,
              image: '/images360/LobbyA_6_Dining.jpg',
              label: 'Corridor Midpoint',
              initialYaw: 190,
              forward: { yaw: 185, pitch: 0 },
              back: { yaw: 359, pitch: 0 },
            },
            {
              id: 13,
              image: '/images360/LobbyA_7_Dining.jpg',
              label: 'G Block Entrance Ahead',
              initialYaw: 220,
              forward: { yaw: 220, pitch: 0 },
              back: { yaw: 0, pitch: 0 },
            },
            {
              id: 14,
              image: '/images360/LobbyA_10_Dining.jpg',
              label: 'G Block Entrance Door',
              initialYaw: 0,
              forward: { yaw: 0, pitch: 0 },
              back: { yaw: 180, pitch: 0 },
            },
            {
              id: 15,
              image: '/images360/LobbyA_11_Dining.jpg',
              label: 'Inside G Block Lobby',
              initialYaw: 0,
              forward: { yaw: 0, pitch: -3 },
              back: { yaw: 180, pitch: -4 },
            },
            {
              id: 16,
              image: '/images360/LobbyA_12_Dining.jpg',
              label: 'Walkway Toward Dining Area',
              initialYaw: 0,
              forward: { yaw: 0, pitch: 0 },
              back: { yaw: 180, pitch: 0 },
            },
            {
              id: 17,
              image: '/images360/LobbyA_13_Dining.jpg',
              label: 'Dining Area First Section',
              initialYaw: 0,
            },
  ],
};

export const borneoJunctionRoute: RouteDefinition = {
  id: 'borneo-junction',
  title: 'Borneo Atrium → Junction',
  fromNode: 'Borneo Atrium',
  toNode: 'Junction',
  scenes: [
            {
                id: 1,
                image: '/images360/L-B-18.jpg',
                label: 'You arrive the Borneo Atrium! Welcome!',
                initialYaw: 180,
                forward: { yaw: 190, pitch: -7 },
            },
            {
                id: 2,
                image: '/images360/L-J-18.jpg',
                label: 'Go up escalator',
                initialYaw: 360,
                forward: { yaw: 360, pitch: 20 },
                back: { yaw: 290, pitch: -12 },
            },
            {
                id: 3,
                image: '/images360/L-J-19.jpg',
                label: 'Junction Balcony',
                initialYaw: 360,
                forward: { yaw: 10, pitch: -12 },
                back: { yaw: 175, pitch: -18 },
            },
            {
                id: 4,
                image: '/images360/L-J-20.jpg',
                label: 'You arrive Junction Level 1',
                initialYaw: 270,
            },  
    ],
};

export const borneoLibraryRoute: RouteDefinition = {
  id: 'borneo-library',
  title: 'Borneo Atrium → Library',
  fromNode: 'Borneo Atrium',
  toNode: 'Library',
  scenes: [
    {
        id: 1,
        image: '/images360/L-B-18.jpg',
        label: 'Borneo Atrium Entrance',
        initialYaw: 180,
        forward: { yaw: 225, pitch: -7 },
    },
    {
        id: 2,
        image: '/images360/L-J-18.jpg',
        label: 'Escalator to Junction Level 1',
        initialYaw: 360,
        forward: { yaw: 360, pitch: 20 },
        back: { yaw: 290, pitch: -12 },
    },
    {
        id: 3,
        image: '/images360/L-J-19.jpg',
        label: 'Junction Balcony',
        initialYaw: 360,
        forward: { yaw: 10, pitch: -12 },
        back: { yaw: 175, pitch: -18 },
    },
    {
        id: 4,
        image: '/images360/L-J-20.jpg',
        label: 'Junction Level 1',
        initialYaw: 90,
        forward: { yaw: 90, pitch: -4 },
        back: { yaw: 180, pitch: -4 },
    },
    {
        id: 5,
        image: '/images360/junction-library-1.jpg',
        label: 'Library Main Entrance',
        initialYaw: 180,
        forward: { yaw: 180, pitch: -4 },
        back: { yaw: 0, pitch: -4 },
    },
    {
        id: 6,
        image: '/images360/litojunc3.jpg',
        label: 'Library Lobby – Service Desk Area',
        initialYaw: 120,
        forward: { yaw: 140, pitch: -4 },
        back: { yaw: 350, pitch: -4 },
    },
    {
        id: 7,
        image: '/images360/L-L-3.jpg',
        label: 'Library Interior – Zones Overview',
        initialYaw: 270,
    },
  ],
};

export const borneoSvRoute: RouteDefinition = {
  id: 'borneo-SV',
  title: 'Borneo Atrium → Student Village',
  fromNode: 'Borneo Atrium',
  toNode: 'Student Village',
  scenes: [
            {
                id: 1,
                image: '/images360/L-B-18.jpg',
                label: 'You arrive the Borneo Atrium! Welcome!',
                initialYaw: 180,
                forward: { yaw: 190, pitch: -7 },
            },
            {
                id: 2,
                image: '/images360/L-B-16.jpg',
                label: 'Left side got escalator can go up to Junction',
                initialYaw: 175,
                back : { yaw: 10, pitch: 0 },
                forward : { yaw: 180, pitch: -5 },
            },
            {
                id: 3,
                image: '/images360/L-B-15.jpg',
                label: 'You are almost there',
                initialYaw: 175,
                back : { yaw: 355, pitch: 0 },
                forward : { yaw: 213, pitch: -6 },
            },
            {
                id: 5,
                image: '/images360/L-B-12.jpg',
                label: 'Vending Machine Area',
                initialYaw: 250,
                back : { yaw: 355, pitch: 0 },
                forward : { yaw: 250, pitch: -5 },
            },
            {
                id: 6,
                image: '/images360/L-B-10.jpg',
                label: 'Go Straight',
                initialYaw: 360,
                back : { yaw: 165, pitch: -4 },
                forward : { yaw: 358, pitch: 0 },
            },
            {
                id: 7,
                image: '/images360/L-B-8.jpg',
                label: 'Walkway in Corridor',
                initialYaw: 180,
                back : { yaw: 355, pitch: 0 },
                forward : { yaw: 175, pitch: -4 },
            },
            {
                id: 8,
                image: '/images360/L-B-6.jpg',
                label: 'Walkway in Corridor',
                initialYaw: 90,
                back : { yaw: 355, pitch: 0 },
                forward : { yaw: 89, pitch: -4 },
            },
            {
                id: 9,
                image: '/images360/L-B-3.jpg',
                label: 'Block A Groundfloor Toilet',
                initialYaw: 60,
                back : { yaw: 178, pitch: -5 },
                forward : { yaw: 70, pitch: -6 },
            },
            {
              id: 10,
              image: '/images360/LobbyA_3_Dining.jpg',
              label: 'Lobby A → G Block Corridor Entrance',
              initialYaw: 0,
              forward: { yaw: 0, pitch: 0 },
              back: { yaw: 180, pitch: 0 },
            },
            {
              id: 11,
              image: '/images360/LobbyA_5_Dining.jpg',
              label: 'Connecting Corridor',
              initialYaw: 0,
              forward: { yaw: 0, pitch: 0 },
              back: { yaw: 180, pitch: 0 },
            },
            {
              id: 12,
              image: '/images360/LobbyA_6_Dining.jpg',
              label: 'Corridor Midpoint',
              initialYaw: 190,
              forward: { yaw: 185, pitch: 0 },
              back: { yaw: 359, pitch: 0 },
            },
            {
              id: 13,
              image: '/images360/LobbyA_7_Dining.jpg',
              label: 'G Block Entrance Ahead',
              initialYaw: 220,
              forward: { yaw: 220, pitch: 0 },
              back: { yaw: 0, pitch: 0 },
            },
            {
              id: 14,
              image: '/images360/LobbyA_10_Dining.jpg',
              label: 'G Block Entrance Door',
              initialYaw: 0,
              forward: { yaw: 0, pitch: 0 },
              back: { yaw: 180, pitch: 0 },
            },
            {
              id: 15,
              image: '/images360/LobbyA_11_Dining.jpg',
              label: 'Inside G Block Lobby',
              initialYaw: 0,
              forward: { yaw: 0, pitch: -3 },
              back: { yaw: 180, pitch: -4 },
            },
            {
              id: 16,
              image: '/images360/LobbyA_12_Dining.jpg',
              label: 'Walkway Toward Dining Area',
              initialYaw: 0,
              forward: { yaw: 0, pitch: 0 },
              back: { yaw: 180, pitch: 0 },
            },
            {
              id: 17,
              image: '/images360/LobbyA_13_Dining.jpg',
              label: 'Dining Area First Section',
              initialYaw: 0,
              forward: { yaw: 0, pitch: -3 },
              back: { yaw: 180, pitch: 0 },
            },
            {
              id: 18,
              image: '/images360/LobbyA_17_Dining.jpg',
              label: 'Dining Area Mid Section',
              initialYaw: 0,
              forward: { yaw: 0, pitch: 0 },
              back: { yaw: 180, pitch: 0 },
            },
            {
              id: 19,
              image: '/images360/LobbyA_14_Dining.jpg',
              label: 'Dining Area',
              initialYaw: 0,
              forward: { yaw: 0, pitch: 0 },
              back: { yaw: 185, pitch: -7 },
            },
            {
              id: 18,
              image: '/images360/sv-shub1.jpg',
              label: 'Student Hub Entrance Area',
              initialYaw: 270,
              forward: { yaw: 280, pitch: -3 },
              back: { yaw: 185, pitch: -7 },
            },
            {
              id: 19,
              image: '/images360/sv-shub2.jpg',
              label: 'Student Hub',
              initialYaw: 180,
              forward: { yaw: 190, pitch: -2 },
              back: { yaw: 20, pitch: 0 },
            },
            {
              id: 20,
              image: '/images360/sv-shub3.jpg',
              label: 'Student Hub',
              initialYaw: 180,
              forward: { yaw: 160, pitch: -2 },
              back: { yaw: 0, pitch: 0 },
            },
            {
              id: 21,
              image: '/images360/sv-shub4.jpg',
              label: 'Go On',
              initialYaw: 180,
              forward: { yaw: 180, pitch: 0 },
              back: { yaw: 0, pitch: 0 },
            },
            {
              id: 22,
              image: '/images360/sv-shub5.jpg',
              label: 'Go On',
              initialYaw: 180,
              forward: { yaw: 180, pitch: 0 },
              back: { yaw: 0, pitch: 0 },
            },
            {
              id: 23,
              image: '/images360/sv_outside.jpg',
              label: 'You are arrive SV',
              initialYaw: 0,
            },
  ],
};

export const borneoRoutes = {
  'borneo-mph': borneoMphRoute,
  'borneo-hq': borneoHqRoute,
  'borneo-shub': borneoShubRoute,
  'borneo-gblock': borneoGblockRoute,
  'borneo-dining': borneoDiningRoute,
  'borneo-junction': borneoJunctionRoute,
  'borneo-library': borneoLibraryRoute,
  'borneo-SV': borneoSvRoute,
};