import type { RouteDefinition } from './types';

export const gblockMphRoute: RouteDefinition = {
  id: 'gblock-mph',
  title: 'G Block → MPH',
  fromNode: 'G Block',
  toNode: 'MPH',
  scenes: [
        {
          id: 1,
          image: '/images360/LobbyA_11_Dining.jpg',
          label: "You are at G Block now",
          initialYaw: 180,
          forward: { yaw: 180, pitch: 0 },
        },
        {
          id: 2,
          image: '/images360/LobbyA_9_Dining.jpg',
          label: 'Follow the arrow',
          initialYaw: 180,
          back : { yaw: 0, pitch: 0 },
          forward: { yaw: 180, pitch: 0 },
        },
        {
          id: 3,
          image: '/images360/LobbyA_8_Dining.jpg',
          label: 'Follow the arrow',
          initialYaw: 180,
          back : { yaw: 10, pitch: 0 },
          forward: { yaw: 190, pitch: 0 },
        },
        {
          id: 4,
          image: '/images360/LobbyA_7_Dining.jpg',
          label: 'Lobby G → A Block Corridor Entrance',
          initialYaw: 0,
          back : { yaw: 180, pitch: 0 },
          forward: { yaw: 0, pitch: 0 },
        },
        {
          id: 5,
          image: '/images360/LobbyA_6_Dining.jpg',
          label: 'Lobby G → A Block Corridor Entrance',
          initialYaw: 0,
          back : { yaw: 180, pitch: 0 },
          forward: { yaw: 0, pitch: 0 },
        },
        {
          id: 6,
          image: '/images360/LobbyA_4_Dining.jpg',
          label: 'Lobby G → A Block Corridor Entrance',
          initialYaw: 180,
          back : { yaw: 0, pitch: 0 },
          forward: { yaw: 180, pitch: 0 },
        },
        {
          id: 7,
          image: '/images360/lobby_c1.jpg',
          label: 'Block A Lobby',
          initialYaw: 0,
          forward: { yaw: 360, pitch: 0 },
        },
        {
          id: 8,
          image: '/images360/lobby2.jpg',
          label: 'Outside Block A Lobby',
          initialYaw: 30,
          forward: { yaw: 50, pitch: 0 },
          back: { yaw: 180, pitch: 0 },
        },
        {
          id: 9,
          image: '/images360/L-M-7.jpg',
          label: 'Towards MPH',
          initialYaw: 250,
          forward: { yaw: 235, pitch: 0 },
          back: { yaw: 90, pitch: 0 },
        },
        {
          id: 10,
          image: '/images360/L-M-10.jpg',
          label: 'Go Straight',
          initialYaw: 0,
          forward: { yaw: 353, pitch: 0 },
          back: { yaw: 190, pitch: -4 },
        },
        {
          id: 11,
          image: '/images360/L-M-13.jpg',
          label: 'Ready to turn right into MPH',
          initialYaw: 360,
          forward: { yaw: 360, pitch: 0 },
          back: { yaw: 175, pitch: -5 },
        },
        {
          id: 12,
          image: '/images360/L-M-16.jpg',
          label: 'Enter the MPH Door',
          initialYaw: 360,
          forward: { yaw: 360, pitch: 0 },
          back: { yaw: 87, pitch: -5 },
        },
        {
          id: 13,
          image: '/images360/L-M-17.jpg',
          label: 'Multi Purpose Hall Lobby',
          initialYaw: 345,
          forward: { yaw: 340, pitch: 0 },
          back: { yaw: 165, pitch: -4 },
        },
        {
          id: 14,
          image: '/images360/L-M-18.jpg',
          label: 'You arrived at the MPH! Welcome!',
          initialYaw: 0,
          back: { yaw: 160, pitch: 0 },
        },
  ],
};

export const gblockHqRoute: RouteDefinition = {
  id: 'gblock-hq',
  title: 'G Block → HQ',
  fromNode: 'G Block',
  toNode: 'HQ',
  scenes: [
    {
          id: 1,
          image: '/images360/LobbyA_11_Dining.jpg',
          label: "You are at G Block now",
          initialYaw: 180,
          forward: { yaw: 180, pitch: 0 },
        },
        {
          id: 2,
          image: '/images360/LobbyA_9_Dining.jpg',
          label: 'Follow the arrow',
          initialYaw: 180,
          back : { yaw: 0, pitch: 0 },
          forward: { yaw: 180, pitch: 0 },
        },
        {
          id: 3,
          image: '/images360/LobbyA_8_Dining.jpg',
          label: 'Follow the arrow',
          initialYaw: 180,
          back : { yaw: 10, pitch: 0 },
          forward: { yaw: 190, pitch: 0 },
        },
        {
          id: 4,
          image: '/images360/LobbyA_7_Dining.jpg',
          label: 'Lobby G → A Block Corridor Entrance',
          initialYaw: 0,
          back : { yaw: 180, pitch: 0 },
          forward: { yaw: 0, pitch: 0 },
        },
        {
          id: 5,
          image: '/images360/LobbyA_6_Dining.jpg',
          label: 'Lobby G → A Block Corridor Entrance',
          initialYaw: 0,
          back : { yaw: 180, pitch: 0 },
          forward: { yaw: 0, pitch: 0 },
        },
        {
          id: 6,
          image: '/images360/LobbyA_4_Dining.jpg',
          label: 'Lobby G → A Block Corridor Entrance',
          initialYaw: 180,
          back : { yaw: 0, pitch: 0 },
          forward: { yaw: 180, pitch: 0 },
        },
        {
          id: 7,
          image: '/images360/lobby_c1.jpg',
          label: 'Block A Lobby',
          initialYaw: 230,
          forward: { yaw: 243, pitch: 0 },
        },
        {
          id: 8,
          image: '/images360/L-H-2.jpg',
          label: 'Student HQ Entrance',
          initialYaw: 0,
          forward: { yaw: 350, pitch: 0 },
          back: { yaw: 140, pitch: 0 },
        },
        {
          id: 9,
          image: '/images360/L-H-3.jpg',
          label: 'Financial Desk Services Area',
          initialYaw: 18,
          forward: { yaw: 55, pitch: 0 },
          back: { yaw: 160, pitch: 0 },
        },
        {
          id: 10,
          image: '/images360/L-H-4.jpg',
          label: 'Student HQ Lobby',
          initialYaw: 340,
          back: { yaw: 250, pitch: 0 },
        },
  ],
};

export const gblockShubRoute: RouteDefinition = {
  id: 'gblock-shub',
  title: 'G Block → Student Hub',
  fromNode: 'G Block',
  toNode: 'Student Hub',
  scenes: [
        {
          id: 1,
          image: "/images360/LobbyA_9_Dining.jpg",
          label: "West Exit — Emergency Door (GF)",
          initialYaw: 0,
          forward: { yaw: 0, pitch: 0 },
        },
        {
          id: 2,
          image: "/images360/LobbyA_11_Dining.jpg",
          label: "West Exit — Emergency Door (GF)",
          initialYaw: 0,
          forward: { yaw: 0, pitch: 0 },
          back : { yaw: 180, pitch: 0 },
        },
        {
          id: 3,
          image: "/images360/LobbyA_13_Dining.jpg",
          label: "West Exit — Emergency Door (GF)",
          initialYaw: 0,
          forward: { yaw: 0, pitch: 0 },
          back : { yaw: 180, pitch: 0 },
        },
        {
          id: 4,
          image: "/images360/LobbyA_17_Dining.jpg",
          label: "West Exit — Emergency Door (GF)",
          initialYaw: 0,
          forward: { yaw: 0, pitch: 0 },
          back : { yaw: 180, pitch: 0 },
        },
        {
          id: 5,
          image: "/images360/LobbyA_15_Dining.jpg",
          label: "West Exit — Emergency Door (GF)",
          initialYaw: 0,
          forward: { yaw: 10, pitch: 0 },
          back : { yaw: 180, pitch: 0 },
        },
        {
          id: 6,
          image: "/images360/StudentHub2.jpg",
          label: "West Exit — Emergency Door (GF)",
          initialYaw: 0,
          forward: { yaw: 0, pitch: 0 },
          back : { yaw: 180, pitch: 0 },
        },
  ],
};

export const gblockDiningRoute: RouteDefinition = {
  id: 'gblock-dining',
  title: 'G Block → Dining Hall',
  fromNode: 'G Block',
  toNode: 'Dining Hall',
  scenes: [
            {
          id: 1,
          image: "/images360/LobbyA_9_Dining.jpg",
          label: "West Exit — Emergency Door (GF)",
          initialYaw: 0,
          back : { yaw: 180, pitch: 0 },
          forward: { yaw: 0, pitch: 0 },
        },
        {
          id: 2,
          image: "/images360/LobbyA_11_Dining.jpg",
          label: "West Exit — Emergency Door (GF)",
          initialYaw: 0,
          back : { yaw: 180, pitch: 0 },
          forward: { yaw: 0, pitch: 0 },
        },
        {
          id: 3,
          image: "/images360/LobbyA_13_Dining.jpg",
          label: "You are here now",
          initialYaw: 0,
          back : { yaw: 180, pitch: 0 },
        },
  ],
};

export const gblockBorneoRoute: RouteDefinition = {
  id: 'gblock-borneo',
  title: 'G Block → Borneo Atrium',
  fromNode: 'G Block',
  toNode: 'Borneo Atrium',
  scenes: [
            {
          id: 1,
          image: '/images360/LobbyA_11_Dining.jpg',
          label: "You are at G Block now",
          initialYaw: 180,
          forward: { yaw: 180, pitch: 0 },
        },
        {
          id: 2,
          image: '/images360/LobbyA_9_Dining.jpg',
          label: 'Follow the arror',
          initialYaw: 180,
          forward: { yaw: 180, pitch: 0 },
          back: { yaw: 0, pitch: -12 },
        },
        {
          id: 3,
          image: '/images360/LobbyA_8_Dining.jpg',
          label: 'Connecting Corridor',
          initialYaw: 180,
          forward: { yaw: 190, pitch: 0 },
          back: { yaw: 10, pitch: -12 },
        },
        {
          id: 4,
          image: '/images360/LobbyA_7_Dining.jpg',
          label: 'Lobby G → A Block Corridor Entrance',
          initialYaw: 0,
          forward: { yaw: 0, pitch: 0 },
          back: { yaw: 180, pitch: -12 },
        },
        {
          id: 5,
          image: '/images360/LobbyA_6_Dining.jpg',
          label: 'Lobby G → A Block Corridor Entrance',
          initialYaw: 0,
          forward: { yaw: 0, pitch: 0 },
          back: { yaw: 180, pitch: -12 },
        },
        {
          id: 6,
          image: '/images360/LobbyA_4_Dining.jpg',
          label: 'Lobby G → A Block Corridor Entrance',
          initialYaw: 180,
          forward: { yaw: 180, pitch: 0 },
          back: { yaw: 0, pitch: -12 },
        },
        {
          id: 1,
          image: "/images360/L-B-1.jpg",
          label: "You are here • Block A Ground Floor",
          initialYaw: 30,
          forward: { yaw: 30, pitch: 0 },
          back: { yaw: 210, pitch: -12 },
        },
        {
          id: 3,
          image: "/images360/L-B-3.jpg",
          label: "Block A -- Borneo Atrium",
          initialYaw: 180,
          forward: { yaw: 180, pitch: 0 },
          back: { yaw: 0, pitch: -12 },
        },
        {
          id: 7,
          image: "/images360/L-B-7.jpg",
          label: "Block A -- Borneo Atrium",
          initialYaw: 0,
          forward: { yaw: 0, pitch: 0 },
          back: { yaw: 180, pitch: -12 },
        },
        {
          id: 10,
          image: "/images360/L-B-10.jpg",
          label: "Block A -- Borneo Atrium",
          initialYaw: 180,
          forward: { yaw: 180, pitch: 0 },
          back: { yaw: 0, pitch: -12 },
        },
        {
          id: 11,
          image: "/images360/L-B-11.jpg",
          label: "Block A -- Borneo Atrium",
          initialYaw: 0,
          forward: { yaw: 0, pitch: 0 },
          back: { yaw: 180, pitch: -12 },
        },
        {
          id:12,
          image: "/images360/L-B-12.jpg",
          label: "Block A -- Borneo Atrium",
          initialYaw: 0,
          forward: { yaw: 0, pitch: 0 },
          back: { yaw: 180, pitch: -12 },
        },
        {
          id: 14,
          image: "/images360/L-B-14.jpg",
          label: "You are at Borneo Atrium now",
          initialYaw: 0,
          back: { yaw: 180, pitch: -12 },
        },
  ],
};

export const gblockJunctionRoute: RouteDefinition = {
  id: 'gblock-junction',
  title: 'G Block → Junction',
  fromNode: 'G Block',
  toNode: 'Junction',
  scenes: [
            {
          id: 1,
          image: '/images360/LobbyA_11_Dining.jpg',
          label: "You are at G Block now",
          initialYaw: 180,
          forward: { yaw: 180, pitch: 0 },
        },
        {
          id: 2,
          image: '/images360/LobbyA_9_Dining.jpg',
          label: 'Follow the arror',
          initialYaw: 180,
          forward: { yaw: 180, pitch: 0 },
          back: { yaw: 0, pitch: -12 },
        },
        {
          id: 3,
          image: '/images360/LobbyA_8_Dining.jpg',
          label: 'Connecting Corridor',
          initialYaw: 180,
          forward: { yaw: 190, pitch: 0 },
          back: { yaw: 10, pitch: -12 },
        },
        {
          id: 4,
          image: '/images360/LobbyA_7_Dining.jpg',
          label: 'Lobby G → A Block Corridor Entrance',
          initialYaw: 0,
          forward: { yaw: 0, pitch: 0 },
          back: { yaw: 180, pitch: -12 },
        },
        {
          id: 5,
          image: '/images360/LobbyA_6_Dining.jpg',
          label: 'Lobby G → A Block Corridor Entrance',
          initialYaw: 0,
          forward: { yaw: 0, pitch: 0 },
          back: { yaw: 180, pitch: -12 },
        },
        {
          id: 6,
          image: '/images360/LobbyA_4_Dining.jpg',
          label: 'Lobby G → A Block Corridor Entrance',
          initialYaw: 180,
          forward: { yaw: 180, pitch: 0 },
          back: { yaw: 0, pitch: -12 },
        },
        {
          id: 7,
          image: "/images360/L-B-1.jpg",
          label: "You are here • Block A Ground Floor",
          initialYaw: 30,
          forward: { yaw: 30, pitch: 0 },
          back: { yaw: 210, pitch: -12 },
        },
        {
          id: 8,
          image: "/images360/L-B-3.jpg",
          label: "Block A -- Borneo Atrium",
          initialYaw: 180,
          forward: { yaw: 180, pitch: 0 },
          back: { yaw: 0, pitch: -12 },
        },
        {
          id: 9,
          image: "/images360/L-B-7.jpg",
          label: "Block A -- Borneo Atrium",
          initialYaw: 0,
          forward: { yaw: 0, pitch: 0 },
          back: { yaw: 180, pitch: -12 },
        },
        {
          id: 10,
          image: "/images360/L-B-10.jpg",
          label: "Block A -- Borneo Atrium",
          initialYaw: 180,
          forward: { yaw: 180, pitch: 0 },
          back: { yaw: 0, pitch: -12 },
        },
        {
          id: 11,
          image: "/images360/L-B-11.jpg",
          label: "Block A -- Borneo Atrium",
          initialYaw: 0,
          forward: { yaw: 0, pitch: 0 },
          back: { yaw: 180, pitch: -12 },
        },
        {
          id:12,
          image: "/images360/L-B-12.jpg",
          label: "Block A -- Borneo Atrium",
          initialYaw: 0,
          forward: { yaw: 0, pitch: 0 },
          back: { yaw: 180, pitch: -12 },
        },
        {
          id: 14,
          image: "/images360/L-B-14.jpg",
          label: "You are at Borneo Atrium now",
          initialYaw: 0,
          forward: { yaw: 0, pitch: 0 },
          back: { yaw: 180, pitch: -12 },
        },
        {
      id: 8,
      image: '/images360/L-J-16.jpg',
      label: 'Left side got escalator can go up to Junction',
      initialYaw: 325,
      forward: { yaw: 315, pitch: -10 },
      back: { yaw: 180, pitch: -6 },
    },
    {
      id: 9,
      image: '/images360/L-J-18.jpg',
      label: 'Go up escalator',
      initialYaw: 360,
      forward: { yaw: 360, pitch: 20 },
      back: { yaw: 290, pitch: -12 },
    },
    {
      id: 10,
      image: '/images360/L-J-19.jpg',
      label: 'Junction Balcony',
      initialYaw: 360,
      forward: { yaw: 10, pitch: -12 },
      back: { yaw: 175, pitch: -18 },
    },
    {
      id: 11,
      image: '/images360/L-J-20.jpg',
      label: 'You arrive Junction Level 1',
      initialYaw: 270,
      back: { yaw: 180, pitch: -4 },
    },
    ],
};

export const gblockLibraryRoute: RouteDefinition = {
  id: 'gblock-library',
  title: 'G Block → Library',
  fromNode: 'G Block',
  toNode: 'Library',
  scenes: [
    {
          id: 1,
          image: '/images360/LobbyA_11_Dining.jpg',
          label: "You are at G Block now",
          initialYaw: 180,
          forward: { yaw: 180, pitch: 0 },
        },
        {
          id: 2,
          image: '/images360/LobbyA_9_Dining.jpg',
          label: 'Follow the arror',
          initialYaw: 180,
          forward: { yaw: 180, pitch: 0 },
          back: { yaw: 0, pitch: -12 },
        },
        {
          id: 3,
          image: '/images360/LobbyA_8_Dining.jpg',
          label: 'Connecting Corridor',
          initialYaw: 180,
          forward: { yaw: 190, pitch: 0 },
          back: { yaw: 10, pitch: -12 },
        },
        {
          id: 4,
          image: '/images360/LobbyA_7_Dining.jpg',
          label: 'Lobby G → A Block Corridor Entrance',
          initialYaw: 0,
          forward: { yaw: 0, pitch: 0 },
          back: { yaw: 180, pitch: -12 },
        },
        {
          id: 5,
          image: '/images360/LobbyA_6_Dining.jpg',
          label: 'Lobby G → A Block Corridor Entrance',
          initialYaw: 0,
          forward: { yaw: 0, pitch: 0 },
          back: { yaw: 180, pitch: -12 },
        },
        {
          id: 6,
          image: '/images360/LobbyA_4_Dining.jpg',
          label: 'Lobby G → A Block Corridor Entrance',
          initialYaw: 180,
          forward: { yaw: 180, pitch: 0 },
          back: { yaw: 0, pitch: -12 },
        },
        {
          id: 1,
          image: '/images360/lobby_c1.jpg',
          label: 'Block A Lobby',
          initialYaw: 180,
          forward: { yaw: 180, pitch: -9 },
          back: { yaw: 0, pitch: -12 },
        },
        {
          id: 2,
          image: '/images360/lobby_c4.jpg',
          label: 'Use Staircase to go Level 1 Library',
          initialYaw: 100,
          forward: { yaw: 110, pitch: 0 },
          back: { yaw: 330, pitch: 0 },
        },
        {
          id: 3,
          image: '/images360/library_c5.jpg',
          label: 'Go straight to Library Entrance',
          initialYaw: 360,
          forward: { yaw: 355, pitch: 0 },
          back: { yaw: 180, pitch: -30 },
        },
        {
          id: 4,
          image: '/images360/library_c7.jpg',
          label: 'Enter with using Student ID if got.',
          initialYaw: 360,
          forward: { yaw: 355, pitch: 0 },
          back: { yaw: 125, pitch: 0 },
        },
        {
          id: 5,
          image: '/images360/library12.jpg',
          label: 'Library Lobby',
          initialYaw: 30,
          forward: { yaw: 350, pitch: 0 },
          back: { yaw: 65, pitch: 0 },
        },
        {
          id: 6,
          image: '/images360/library_c9.jpg',
          label: 'Quiet Zone',
          initialYaw: 100,
          forward: { yaw: 180, pitch: 0 },
          back: { yaw: 270, pitch: 0 },
        },
        {
          id: 7,
          image: '/images360/library_c10.jpg',
          label: 'Book Section',
          initialYaw: 80,
          back: { yaw: 180, pitch: 0 },
        },
  ],
};

export const gblockSvRoute: RouteDefinition = {
  id: 'gblock-SV',
  title: 'G Block → Student Village',
  fromNode: 'G Block',
  toNode: 'Student Village',
  scenes: [
        {
          id: 1,
          image: "/images360/LobbyA_9_Dining.jpg",
          label: "West Exit — Emergency Door (GF)",
          initialYaw: 0,
          back : { yaw: 180, pitch: 0 },
          forward: { yaw: 0, pitch: 0 },
        },
        {
          id: 2,
          image: "/images360/LobbyA_11_Dining.jpg",
          label: "West Exit — Emergency Door (GF)",
          initialYaw: 0,
          back : { yaw: 180, pitch: 0 },
          forward: { yaw: 0, pitch: 0 },
        },
        {
          id: 3,
          image: "/images360/LobbyA_13_Dining.jpg",
          label: "West Exit — Emergency Door (GF)",
          initialYaw: 0,
          back : { yaw: 180, pitch: 0 },
          forward: { yaw: 0, pitch: 0 },
        },
        {
          id: 4,
          image: "/images360/LobbyA_17_Dining.jpg",
          label: "West Exit — Emergency Door (GF)",
          initialYaw: 0,
          back : { yaw: 180, pitch: 0 },
          forward: { yaw: 0, pitch: 0 },
        },
        {
          id: 5,
          image: "/images360/LobbyA_14_Dining.jpg",
          label: "West Exit — Emergency Door (GF)",
          initialYaw: 345,
          back : { yaw: 120, pitch: 0 },
          forward: { yaw: 300, pitch: 0 },
        },
        {
          id: 6,
          image: "/images360/mph_exit_9.jpg",
          label: "Towards MPH",
          initialYaw: 180,
          back : { yaw: 0, pitch: 0 },
          forward: { yaw: 180, pitch: 0 },
        },
        {
          id: 7,
          image: "/images360/mph_exit_3.jpg",
          label: "Go Straight",
          initialYaw: 300,
          back : { yaw: 120, pitch: 0 },
          forward: { yaw: 300, pitch: 0 },
        },
        {
          id: 8,
          image: "/images360/mph_exit_6.jpg",
          label: "Head towards Leisure Area",
          initialYaw: 0,
          back : { yaw: 180, pitch: 0 },
          forward: { yaw: 0, pitch: 0 },
        },
        {
          id: 9,
          image: "/images360/mph_exit_7.jpg",
          label: "You are here",
          initialYaw: 90,
          back : { yaw: 180, pitch: 0 },
        },
  ],
};

export const borneoRoutes = {
    'gblock-mph': gblockMphRoute,
    'gblock-hq': gblockHqRoute,
    'gblock-shub': gblockShubRoute,
    'gblock-dining':gblockDiningRoute,
    'gblock-borneo': gblockBorneoRoute,
    'gblock-junction': gblockJunctionRoute,
    'gblock-library': gblockLibraryRoute,
    'gblock-SV': gblockSvRoute,
};
