import type { RouteDefinition } from './types';

export const libraryMphRoute: RouteDefinition = {
  id: 'library-mph',
  title: 'Library → MPH',
  fromNode: 'Library',
  toNode: 'MPH',
  scenes: [
            {
              id: 1,
              image: '/images360/library12.jpg',
              label: 'Library Lobby',
              initialYaw: 50,
              forward: { yaw: 65, pitch: 0 },
            },
            {
              id: 2,
              image: '/images360/library_c7.jpg',
              label: 'Go out Library Lobby and turn left.',
              initialYaw: 170,
              back: { yaw: 355, pitch: 0 },
              forward: { yaw: 125, pitch: 0 },
            },
            {
              id: 3,
              image: '/images360/library_c5.jpg',
              label: 'Go Down Using Staircase',
              initialYaw: 180,
              back: { yaw: 355, pitch: 0 },
              forward: { yaw: 180, pitch: -30 },
            },
            {
              id: 4,
              image: '/images360/lobby_c4.jpg',
              label: 'Go to Lobby',
              initialYaw: 10,
              back: { yaw: 110, pitch: 0 },
              forward: { yaw: 355, pitch: -4 },
            },
            {
              id: 5,
              image: '/images360/lobby_c1.jpg',
              label: 'Block A Lobby',
              initialYaw: 0,
              forward: { yaw: 360, pitch: 0 },
            },
            {
              id: 6,
              image: '/images360/lobby2.jpg',
              label: 'Outside Block A Lobby',
              initialYaw: 30,
              forward: { yaw: 50, pitch: 0 },
              back: { yaw: 180, pitch: 0 },
            },
            {
              id: 7,
              image: '/images360/L-M-7.jpg',
              label: 'Towards MPH',
              initialYaw: 250,
              forward: { yaw: 235, pitch: 0 },
              back: { yaw: 90, pitch: 0 },
            },
            {
              id: 8,
              image: '/images360/L-M-10.jpg',
              label: 'Go Straight',
              initialYaw: 0,
              forward: { yaw: 353, pitch: 0 },
              back: { yaw: 190, pitch: -4 },
            },
            {
              id: 9,
              image: '/images360/L-M-13.jpg',
              label: 'Ready to turn right into MPH',
              initialYaw: 360,
              forward: { yaw: 360, pitch: 0 },
              back: { yaw: 175, pitch: -5 },
            },
            {
              id: 10,
              image: '/images360/L-M-16.jpg',
              label: 'Enter the MPH Door',
              initialYaw: 360,
              forward: { yaw: 360, pitch: 0 },
              back: { yaw: 87, pitch: -5 },
            },
            {
              id: 11,
              image: '/images360/L-M-17.jpg',
              label: 'Multi Purpose Hall Lobby',
              initialYaw: 345,
              forward: { yaw: 340, pitch: 0 },
              back: { yaw: 165, pitch: -4 },
            },
            {
              id: 12,
              image: '/images360/L-M-18.jpg',
              label: 'You arrived at the MPH! Welcome!',
              initialYaw: 0,
              back: { yaw: 160, pitch: 0 },
            },
  ],
};

export const libraryHqRoute: RouteDefinition = {
  id: 'library-hq',
  title: 'Library → HQ',
  fromNode: 'Library',
  toNode: 'HQ',
  scenes: [
            {
              id: 1,
              image: '/images360/library12.jpg',
              label: 'Library Lobby',
              initialYaw: 50,
              forward: { yaw: 65, pitch: 0 },
            },
            {
              id: 2,
              image: '/images360/library_c7.jpg',
              label: 'Go out Library Lobby and turn left.',
              initialYaw: 170,
              back: { yaw: 355, pitch: 0 },
              forward: { yaw: 125, pitch: 0 },
            },
            {
              id: 3,
              image: '/images360/library_c5.jpg',
              label: 'Go Down Using Staircase',
              initialYaw: 180,
              back: { yaw: 355, pitch: 0 },
              forward: { yaw: 180, pitch: -30 },
            },
            {
              id: 4,
              image: '/images360/lobby_c4.jpg',
              label: 'Turn Left',
              initialYaw: 10,
              back: { yaw: 110, pitch: 0 },
              forward: { yaw: 355, pitch: -4 },
            },
            {
              id: 2,
              image: '/images360/L-H-2.jpg',
              label: 'Student HQ Entrance',
              initialYaw: 0,
              forward: { yaw: 350, pitch: 0 },
              back: { yaw: 140, pitch: 0 },
            },
            {
              id: 3,
              image: '/images360/L-H-3.jpg',
              label: 'Financial Desk Services Area',
              initialYaw: 18,
              forward: { yaw: 55, pitch: 0 },
              back: { yaw: 160, pitch: 0 },
            },
            {
              id: 4,
              image: '/images360/L-H-4.jpg',
              label: 'Student HQ Lobby',
              initialYaw: 340,
            },
  ],
};

export const libraryShubRoute: RouteDefinition = {
  id: 'library-shub',
  title: 'Library → Student Hub',
  fromNode: 'Library',
  toNode: 'Student Hub',
  scenes: [
            {
              id: 1,
              image: '/images360/library12.jpg',
              label: 'Library Lobby',
              initialYaw: 50,
              forward: { yaw: 65, pitch: 0 },
            },
            {
              id: 2,
              image: '/images360/library_c7.jpg',
              label: 'Go out Library Lobby and turn left.',
              initialYaw: 170,
              back: { yaw: 355, pitch: 0 },
              forward: { yaw: 125, pitch: 0 },
            },
            {
              id: 3,
              image: '/images360/library_c5.jpg',
              label: 'Go Down Using Staircase',
              initialYaw: 180,
              back: { yaw: 355, pitch: 0 },
              forward: { yaw: 180, pitch: -30 },
            },
            {
              id: 4,
              image: '/images360/lobby_c4.jpg',
              label: 'Turn Right',
              initialYaw: 10,
              back: { yaw: 110, pitch: 0 },
              forward: { yaw: 355, pitch: -4 },
            },
            {
              id: 5,
              image: '/images360/LobbyA_3_Dining.jpg',
              label: 'Lobby A → G Block Corridor Entrance',
              initialYaw: 0,
              forward: { yaw: 0, pitch: 0 },
              back: { yaw: 180, pitch: 0 },
            },
            {
              id: 6,
              image: '/images360/LobbyA_5_Dining.jpg',
              label: 'Connecting Corridor',
              initialYaw: 0,
              forward: { yaw: 0, pitch: 0 },
              back: { yaw: 180, pitch: 0 },
            },
            {
              id: 7,
              image: '/images360/LobbyA_6_Dining.jpg',
              label: 'Corridor Midpoint',
              initialYaw: 190,
              forward: { yaw: 185, pitch: 0 },
              back: { yaw: 359, pitch: 0 },
            },
            {
              id: 8,
              image: '/images360/LobbyA_7_Dining.jpg',
              label: 'G Block Entrance Ahead',
              initialYaw: 220,
              forward: { yaw: 220, pitch: 0 },
              back: { yaw: 0, pitch: 0 },
            },
            {
              id: 9,
              image: '/images360/LobbyA_10_Dining.jpg',
              label: 'G Block Entrance Door',
              initialYaw: 0,
              forward: { yaw: 0, pitch: 0 },
              back: { yaw: 180, pitch: 0 },
            },
            {
              id: 10,
              image: '/images360/LobbyA_11_Dining.jpg',
              label: 'Inside G Block Lobby',
              initialYaw: 0,
              forward: { yaw: 0, pitch: -3 },
              back: { yaw: 180, pitch: -4 },
            },
            {
              id: 11,
              image: '/images360/LobbyA_12_Dining.jpg',
              label: 'Walkway Toward Dining Area',
              initialYaw: 0,
              forward: { yaw: 0, pitch: 0 },
              back: { yaw: 180, pitch: 0 },
            },
            {
              id: 12,
              image: '/images360/LobbyA_13_Dining.jpg',
              label: 'Dining Area First Section',
              initialYaw: 0,
              forward: { yaw: 0, pitch: -3 },
              back: { yaw: 180, pitch: 0 },
            },
            {
              id: 13,
              image: '/images360/LobbyA_17_Dining.jpg',
              label: 'Dining Area Mid Section',
              initialYaw: 0,
              forward: { yaw: 0, pitch: 0 },
              back: { yaw: 180, pitch: 0 },
            },
            {
              id: 14,
              image: '/images360/LobbyA_14_Dining.jpg',
              label: 'Dining Area',
              initialYaw: 0,
              forward: { yaw: 0, pitch: 0 },
              back: { yaw: 185, pitch: -7 },
            },
            {
              id: 15,
              image: '/images360/LobbyA_15_Dining.jpg',
              label: 'Student Hub Entrance Area',
              initialYaw: 15,
              forward: { yaw: 15, pitch: -3 },
              back: { yaw: 185, pitch: -7 },
            },
            {
              id: 16,
              image: '/images360/LobbyA_16_Dining.jpg',
              label: 'Inside Student Hub',
              initialYaw: 0,
              forward: { yaw: 0, pitch: -3 },
              back: { yaw: 176, pitch: -6 },
            },
            {
              id: 17,
              image: '/images360/StudentHub1.jpg',
              label: 'Inside Student Hub',
              initialYaw: 0,
            }, 
  ],
};

export const libraryDiningRoute: RouteDefinition = {
  id: 'library-dining',
  title: 'Library → Dining Hall',
  fromNode: 'Library',
  toNode: 'Dining Hall',
  scenes: [
            {
              id: 1,
              image: '/images360/library12.jpg',
              label: 'Library Lobby',
              initialYaw: 50,
              forward: { yaw: 65, pitch: 0 },
            },
            {
              id: 2,
              image: '/images360/library_c7.jpg',
              label: 'Go out Library Lobby and turn left.',
              initialYaw: 170,
              back: { yaw: 355, pitch: 0 },
              forward: { yaw: 125, pitch: 0 },
            },
            {
              id: 3,
              image: '/images360/library_c5.jpg',
              label: 'Go Down Using Staircase',
              initialYaw: 180,
              back: { yaw: 355, pitch: 0 },
              forward: { yaw: 180, pitch: -30 },
            },
            {
              id: 4,
              image: '/images360/lobby_c4.jpg',
              label: 'Turn Right',
              initialYaw: 10,
              back: { yaw: 110, pitch: 0 },
              forward: { yaw: 355, pitch: -4 },
            },
            {
              id: 5,
              image: '/images360/LobbyA_3_Dining.jpg',
              label: 'Lobby A → G Block Corridor Entrance',
              initialYaw: 0,
              forward: { yaw: 0, pitch: 0 },
              back: { yaw: 180, pitch: 0 },
            },
            {
              id: 6,
              image: '/images360/LobbyA_5_Dining.jpg',
              label: 'Connecting Corridor',
              initialYaw: 0,
              forward: { yaw: 0, pitch: 0 },
              back: { yaw: 180, pitch: 0 },
            },
            {
              id: 7,
              image: '/images360/LobbyA_6_Dining.jpg',
              label: 'Corridor Midpoint',
              initialYaw: 190,
              forward: { yaw: 185, pitch: 0 },
              back: { yaw: 359, pitch: 0 },
            },
            {
              id: 8,
              image: '/images360/LobbyA_7_Dining.jpg',
              label: 'G Block Entrance Ahead',
              initialYaw: 220,
              forward: { yaw: 220, pitch: 0 },
              back: { yaw: 0, pitch: 0 },
            },
            {
              id: 9,
              image: '/images360/LobbyA_10_Dining.jpg',
              label: 'G Block Entrance Door',
              initialYaw: 0,
              forward: { yaw: 0, pitch: 0 },
              back: { yaw: 180, pitch: 0 },
            },
            {
              id: 10,
              image: '/images360/LobbyA_11_Dining.jpg',
              label: 'Inside G Block Lobby',
              initialYaw: 0,
              forward: { yaw: 0, pitch: -3 },
              back: { yaw: 180, pitch: -4 },
            },
            {
              id: 11,
              image: '/images360/LobbyA_12_Dining.jpg',
              label: 'Walkway Toward Dining Area',
              initialYaw: 0,
              forward: { yaw: 0, pitch: 0 },
              back: { yaw: 180, pitch: 0 },
            },
            {
              id: 12,
              image: '/images360/LobbyA_13_Dining.jpg',
              label: 'Dining Area First Section',
              initialYaw: 0,
            },
  ],
};

export const libraryBorneoRoute: RouteDefinition = {
  id: 'library-borneo',
  title: 'Library → Borneo Atrium',
  fromNode: 'Library',
  toNode: 'Borneo Atrium',
  scenes: [
            {
              id: 1,
              image: '/images360/library12.jpg',
              label: 'Library Lobby',
              initialYaw: 85,
              forward: { yaw: 85, pitch: -4 },
            },
            {
              id: 2,
              image: '/images360/litojunc1.jpg',
              label: 'Library → Junction',
              initialYaw: 0,
              forward: { yaw: 355, pitch: -4 },
              back: { yaw: 180, pitch: -4 },
            },
            {
              id: 3,
              image: '/images360/litojunc2.jpg',
              label: 'Library → Junction',
              initialYaw: 0,
              forward: { yaw: 355, pitch: -4 },
              back: { yaw: 80, pitch: -4 },
            },
            {
              id: 4,
              image: '/images360/litojunc3.jpg',
              label: 'Go Out Barrier Gates',
              initialYaw: 0,
              forward: { yaw: 357, pitch: -8 },
              back: { yaw: 140, pitch: -4 },
            },
            {
              id: 5,
              image: '/images360/litojunc4.jpg',
              label: 'You have arrive Junction',
              initialYaw: 10,
              forward: { yaw: 5, pitch: -4 },
              back: { yaw: 257, pitch: -4 },
            },
            {
              id: 6,
              image: '/images360/L-J-19.jpg',
              label: 'Go down escalator',
              initialYaw: 180,
              forward: { yaw: 180, pitch: -15 },
              back: { yaw: 360, pitch: -10 },
            },
            {
              id: 7,
              image: '/images360/L-J-18.jpg',
              label: 'You are almost there',
              initialYaw: 220,
              forward: { yaw: 220, pitch: -4 },
              back: { yaw: 360, pitch: 20 },
            },
            {
              id: 8,
              image: '/images360/L-B-18.jpg',
              label: 'You arrive the Borneo Atrium! Welcome!',
              initialYaw: 180,
            },  
  ],
};

export const libraryGblockRoute: RouteDefinition = {
  id: 'library-gblock',
  title: 'Library → G Block',
  fromNode: 'Library',
  toNode: 'G Block',
  scenes: [
            {
              id: 1,
              image: '/images360/library12.jpg',
              label: 'Library Lobby',
              initialYaw: 50,
              forward: { yaw: 65, pitch: 0 },
            },
            {
              id: 2,
              image: '/images360/library_c7.jpg',
              label: 'Go out Library Lobby and turn left.',
              initialYaw: 170,
              back: { yaw: 355, pitch: 0 },
              forward: { yaw: 125, pitch: 0 },
            },
            {
              id: 3,
              image: '/images360/library_c5.jpg',
              label: 'Go Down Using Staircase',
              initialYaw: 180,
              back: { yaw: 355, pitch: 0 },
              forward: { yaw: 180, pitch: -30 },
            },
            {
              id: 4,
              image: '/images360/lobby_c4.jpg',
              label: 'Turn Right',
              initialYaw: 10,
              back: { yaw: 110, pitch: 0 },
              forward: { yaw: 355, pitch: -4 },
            },
            {
              id: 5,
              image: '/images360/LobbyA_3_Dining.jpg',
              label: 'Lobby A → G Block Corridor Entrance',
              initialYaw: 0,
              forward: { yaw: 0, pitch: 0 },
              back: { yaw: 180, pitch: 0 },
            },
            {
              id: 6,
              image: '/images360/LobbyA_5_Dining.jpg',
              label: 'Connecting Corridor',
              initialYaw: 0,
              forward: { yaw: 0, pitch: 0 },
              back: { yaw: 180, pitch: 0 },
            },
            {
              id: 7,
              image: '/images360/LobbyA_6_Dining.jpg',
              label: 'Corridor Midpoint',
              initialYaw: 190,
              forward: { yaw: 185, pitch: 0 },
              back: { yaw: 359, pitch: 0 },
            },
            {
              id: 8,
              image: '/images360/LobbyA_7_Dining.jpg',
              label: 'G Block Entrance Ahead',
              initialYaw: 220,
              forward: { yaw: 220, pitch: 0 },
              back: { yaw: 0, pitch: 0 },
            },
            {
              id: 9,
              image: '/images360/LobbyA_10_Dining.jpg',
              label: 'G Block Entrance Door',
              initialYaw: 0,
              forward: { yaw: 0, pitch: 0 },
              back: { yaw: 180, pitch: 0 },
            },
            {
              id: 10,
              image: '/images360/LobbyA_11_Dining.jpg',
              label: 'Inside G Block Lobby',
              initialYaw: 320,
            },
    ],
};

export const libraryJunctionRoute: RouteDefinition = {
  id: 'library-junction',
  title: 'Library → Junction',
  fromNode: 'Library',
  toNode: 'Junction',
  scenes: [
            {
              id: 1,
              image: '/images360/library12.jpg',
              label: 'Library Lobby',
              initialYaw: 85,
              forward: { yaw: 85, pitch: -4 },
            },
            {
              id: 2,
              image: '/images360/litojunc1.jpg',
              label: 'Library → Junction',
              initialYaw: 0,
              forward: { yaw: 355, pitch: -4 },
              back: { yaw: 180, pitch: -4 },
            },
            {
              id: 3,
              image: '/images360/litojunc2.jpg',
              label: 'Library → Junction',
              initialYaw: 0,
              forward: { yaw: 355, pitch: -4 },
              back: { yaw: 80, pitch: -4 },
            },
            {
              id: 4,
              image: '/images360/litojunc3.jpg',
              label: 'Go Out Barrier Gates',
              initialYaw: 0,
              forward: { yaw: 357, pitch: -8 },
              back: { yaw: 140, pitch: -4 },
            },
            {
              id: 5,
              image: '/images360/litojunc4.jpg',
              label: 'You have arrive Junction',
              initialYaw: 120,
            },
  ],
};

export const librarySvRoute: RouteDefinition = {
  id: 'library-SV',
  title: 'Library → Student Village',
  fromNode: 'Library',
  toNode: 'Student Village',
  scenes: [
    {
              id: 1,
              image: '/images360/library12.jpg',
              label: 'Library Lobby',
              initialYaw: 50,
              forward: { yaw: 65, pitch: 0 },
            },
            {
              id: 2,
              image: '/images360/library_c7.jpg',
              label: 'Go out Library Lobby and turn left.',
              initialYaw: 170,
              back: { yaw: 355, pitch: 0 },
              forward: { yaw: 125, pitch: 0 },
            },
            {
              id: 3,
              image: '/images360/library_c5.jpg',
              label: 'Go Down Using Staircase',
              initialYaw: 180,
              back: { yaw: 355, pitch: 0 },
              forward: { yaw: 180, pitch: -30 },
            },
            {
              id: 4,
              image: '/images360/lobby_c4.jpg',
              label: 'Turn Right',
              initialYaw: 10,
              back: { yaw: 110, pitch: 0 },
              forward: { yaw: 355, pitch: -4 },
            },
            {
              id: 5,
              image: '/images360/LobbyA_3_Dining.jpg',
              label: 'Lobby A → G Block Corridor Entrance',
              initialYaw: 0,
              forward: { yaw: 0, pitch: 0 },
              back: { yaw: 180, pitch: 0 },
            },
            {
              id: 6,
              image: '/images360/LobbyA_5_Dining.jpg',
              label: 'Connecting Corridor',
              initialYaw: 0,
              forward: { yaw: 0, pitch: 0 },
              back: { yaw: 180, pitch: 0 },
            },
            {
              id: 7,
              image: '/images360/LobbyA_6_Dining.jpg',
              label: 'Corridor Midpoint',
              initialYaw: 190,
              forward: { yaw: 185, pitch: 0 },
              back: { yaw: 359, pitch: 0 },
            },
            {
              id: 8,
              image: '/images360/LobbyA_7_Dining.jpg',
              label: 'G Block Entrance Ahead',
              initialYaw: 220,
              forward: { yaw: 220, pitch: 0 },
              back: { yaw: 0, pitch: 0 },
            },
            {
              id: 9,
              image: '/images360/LobbyA_10_Dining.jpg',
              label: 'G Block Entrance Door',
              initialYaw: 0,
              forward: { yaw: 0, pitch: 0 },
              back: { yaw: 180, pitch: 0 },
            },
            {
              id: 7,
              image: '/images360/LobbyA_11_Dining.jpg',
              label: 'Inside G Block Lobby',
              initialYaw: 0,
              forward: { yaw: 0, pitch: -3 },
              back: { yaw: 180, pitch: -4 },
            },
            {
              id: 8,
              image: '/images360/LobbyA_12_Dining.jpg',
              label: 'Walkway Toward Dining Area',
              initialYaw: 0,
              forward: { yaw: 0, pitch: 0 },
              back: { yaw: 180, pitch: 0 },
            },
            {
              id: 9,
              image: '/images360/LobbyA_13_Dining.jpg',
              label: 'Dining Area First Section',
              initialYaw: 0,
              forward: { yaw: 0, pitch: -3 },
              back: { yaw: 180, pitch: 0 },
            },
            {
              id: 10,
              image: '/images360/LobbyA_17_Dining.jpg',
              label: 'Dining Area Mid Section',
              initialYaw: 0,
              forward: { yaw: 0, pitch: 0 },
              back: { yaw: 180, pitch: 0 },
            },
            {
              id: 11,
              image: '/images360/LobbyA_14_Dining.jpg',
              label: 'Dining Area',
              initialYaw: 0,
              forward: { yaw: 0, pitch: 0 },
              back: { yaw: 185, pitch: -7 },
            },
            {
              id: 17,
              image: '/images360/sv-shub1.jpg',
              label: 'Student Hub Entrance Area',
              initialYaw: 270,
              forward: { yaw: 280, pitch: -3 },
              back: { yaw: 185, pitch: -7 },
            },
            {
              id: 18,
              image: '/images360/sv-shub2.jpg',
              label: 'Student Hub',
              initialYaw: 180,
              forward: { yaw: 190, pitch: -2 },
              back: { yaw: 20, pitch: 0 },
            },
            {
              id: 19,
              image: '/images360/sv-shub3.jpg',
              label: 'Student Hub',
              initialYaw: 180,
              forward: { yaw: 160, pitch: -2 },
              back: { yaw: 0, pitch: 0 },
            },
            {
              id: 20,
              image: '/images360/sv-shub4.jpg',
              label: 'Go On',
              initialYaw: 180,
              forward: { yaw: 180, pitch: 0 },
              back: { yaw: 0, pitch: 0 },
            },
            {
              id: 21,
              image: '/images360/sv-shub5.jpg',
              label: 'Go On',
              initialYaw: 180,
              forward: { yaw: 180, pitch: 0 },
              back: { yaw: 0, pitch: 0 },
            },
            {
              id: 22,
              image: '/images360/sv_outside.jpg',
              label: 'You are arrive SV',
              initialYaw: 0,
            },
  ],
};

export const borneoRoutes = {
    'library-mph': libraryMphRoute,
    'library-hq': libraryHqRoute,
    'library-shub': libraryShubRoute,
    'library-dining':libraryDiningRoute,
    'library-borneo': libraryBorneoRoute,
    'library-gblock': libraryGblockRoute,
    'library-junction': libraryJunctionRoute,
    'library-SV': librarySvRoute,
};