import type { RouteDefinition } from './types';

// Borneo Atrium
export const lobbyBorneoRoute: RouteDefinition = {
  id: 'lobby-borneo',
  title: 'Lobby → Borneo Atrium',
  fromNode: 'Block A Lobby',
  toNode: 'Borneo Atrium',
  scenes: [
            {
            id: 1,
                image: '/images360/L-B-1.jpg',
                label: 'Block A Lobby',
                initialYaw: 20,
                forward: { yaw: 30, pitch: 0 },
            },
            {
                id: 2,
                image: '/images360/L-B-3.jpg',
                label: 'Block A Groundfloor Toilet',
                initialYaw: 175,
                forward: { yaw: 178, pitch: -5 },
                back: { yaw: 70, pitch: -6 },
            },
            {
                id: 3,
                image: '/images360/L-B-6.jpg',
                label: 'Walkway in Corridor',
                initialYaw: 360,
                forward: { yaw: 355, pitch: 0 },
                back: { yaw: 89, pitch: -4 },
            },
            {
                id: 4,
                image: '/images360/L-B-8.jpg',
                label: 'Walkway in Corridor',
                initialYaw: 360,
                forward: { yaw: 355, pitch: 0 },
                back: { yaw: 175, pitch: -4 },
            },
            {
                id: 5,
                image: '/images360/L-B-10.jpg',
                label: 'Go Straight and ready turn left',
                initialYaw: 180,
                forward: { yaw: 165, pitch: -4 },
                back: { yaw: 358, pitch: 0 },
            },
            {
                id: 6,
                image: '/images360/L-B-12.jpg',
                label: 'Leisure Zone',
                initialYaw: 10,
                forward: { yaw: 355, pitch: 0 },
                back: { yaw: 250, pitch: -5 },
            },
            {
                id: 7,
                image: '/images360/L-B-15.jpg',
                label: 'You are almost there',
                initialYaw: 355,
                forward: { yaw: 355, pitch: 0 },
                back: { yaw: 213, pitch: -6 },
            },
            {
                id: 8,
                image: '/images360/L-B-16.jpg',
                label: 'Left side got escalator can go up to Junction',
                initialYaw: 355,
                forward: { yaw: 10, pitch: 0 },
                back: { yaw: 180, pitch: -5 },
            },
            {
                id: 9,
                image: '/images360/L-B-18.jpg',
                label: 'You arrive the Borneo Atrium! Welcome!',
                initialYaw: 180,
                // back: { yaw: 190, pitch: -7 },
            },    
  ],
  nextRouteIds: ['borneo-mph', 'borneo-shub', 'borneo-dining', 'borneo-gblock', 'borneo-hq', 'borneo-junction', 'borneo-library'],
};

// MPH
export const lobbyMphRoute: RouteDefinition = {
  id: 'lobby-mph',
  title: 'Lobby → Multi Purpose Hall',
  fromNode: 'Block A Lobby',
  toNode: 'Multi Purpose Hall',
  scenes: [
    {
      id: 1,
      image: '/images360/lobby_c1.jpg',
      label: 'Block A Lobby',
      initialYaw: 0,
      forward: { yaw: 360, pitch: 0 },
    },
    {
      id: 2,
      image: '/images360/lobby2.jpg',
      label: 'Outside Block A Lobby',
      initialYaw: 30,
      forward: { yaw: 50, pitch: 0 },
      back: { yaw: 180, pitch: 0 },
    },
    {
      id: 3,
      image: '/images360/L-M-7.jpg',
      label: 'Towards MPH',
      initialYaw: 250,
      forward: { yaw: 235, pitch: 0 },
      back: { yaw: 90, pitch: 0 },
    },
    {
      id: 4,
      image: '/images360/L-M-10.jpg',
      label: 'Go Straight',
      initialYaw: 0,
      forward: { yaw: 353, pitch: 0 },
      back: { yaw: 190, pitch: -4 },
    },
    {
      id: 5,
      image: '/images360/L-M-13.jpg',
      label: 'Ready to turn right into MPH',
      initialYaw: 360,
      forward: { yaw: 360, pitch: 0 },
      back: { yaw: 175, pitch: -5 },
    },
    {
      id: 6,
      image: '/images360/L-M-16.jpg',
      label: 'Enter the MPH Door',
      initialYaw: 360,
      forward: { yaw: 360, pitch: 0 },
      back: { yaw: 87, pitch: -5 },
    },
    {
      id: 7,
      image: '/images360/L-M-17.jpg',
      label: 'Multi Purpose Hall Lobby',
      initialYaw: 345,
      forward: { yaw: 340, pitch: 0 },
      back: { yaw: 165, pitch: -4 },
    },
    {
      id: 8,
      image: '/images360/L-M-18.jpg',
      label: 'You arrived at the MPH! Welcome!',
      initialYaw: 0,
      back: { yaw: 160, pitch: 0 },
    },
  ],
  nextRouteIds: ['mph-borneo', 'mph-library', 'mph-junction'],
};

// Dininig
export const lobbyDiningRoute: RouteDefinition = {
  id: 'lobby-dining',
  title: 'Lobby → Dining Hall',
  fromNode: 'Block A Lobby',
  toNode: 'Dining Hall',
  scenes: [
    {
      id: 1,
      image: '/images360/LobbyA_1_Dining.jpg',
      label: 'A Block Lobby',
      initialYaw: 0,
      forward: { yaw: 0, pitch: 0 },
    },
    {
      id: 2,
      image: '/images360/LobbyA_3_Dining.jpg',
      label: 'Lobby A → G Block Corridor Entrance',
      initialYaw: 0,
      forward: { yaw: 0, pitch: 0 },
      back: { yaw: 180, pitch: 0 },
    },
    {
      id: 3,
      image: '/images360/LobbyA_5_Dining.jpg',
      label: 'Connecting Corridor',
      initialYaw: 0,
      forward: { yaw: 0, pitch: 0 },
      back: { yaw: 180, pitch: 0 },
    },
    {
      id: 4,
      image: '/images360/LobbyA_6_Dining.jpg',
      label: 'Corridor Midpoint',
      initialYaw: 190,
      forward: { yaw: 185, pitch: 0 },
      back: { yaw: 359, pitch: 0 },
    },
    {
      id: 5,
      image: '/images360/LobbyA_7_Dining.jpg',
      label: 'G Block Entrance Ahead',
      initialYaw: 220,
      forward: { yaw: 220, pitch: 0 },
      back: { yaw: 0, pitch: 0 },
    },
    {
      id: 6,
      image: '/images360/LobbyA_10_Dining.jpg',
      label: 'G Block Entrance Door',
      initialYaw: 0,
      forward: { yaw: 0, pitch: 0 },
      back: { yaw: 180, pitch: 0 },
    },
    {
      id: 7,
      image: '/images360/LobbyA_11_Dining.jpg',
      label: 'Inside G Block Lobby',
      initialYaw: 0,
      forward: { yaw: 0, pitch: -3 },
      back: { yaw: 180, pitch: -4 },
    },
    {
      id: 8,
      image: '/images360/LobbyA_12_Dining.jpg',
      label: 'Walkway Toward Dining Area',
      initialYaw: 0,
      forward: { yaw: 0, pitch: 0 },
      back: { yaw: 180, pitch: 0 },
    },
    {
      id: 9,
      image: '/images360/LobbyA_13_Dining.jpg',
      label: 'Dining Area First Section',
      initialYaw: 0,
      forward: { yaw: 0, pitch: -3 },
    },

  ],
  nextRouteIds: ['borneo-mph', 'mph-borneo'],
};

// Student Hub
export const lobbyShubRoute: RouteDefinition = {
  id: 'lobby-shub',
  title: 'Lobby → Student Hub',
  fromNode: 'Block A Lobby',
  toNode: 'Student Hub',
  scenes: [
    {
      id: 1,
      image: '/images360/LobbyA_1_Dining.jpg',
      label: 'A Block Lobby',
      initialYaw: 0,
      forward: { yaw: 0, pitch: 0 },
    },
    {
      id: 2,
      image: '/images360/LobbyA_3_Dining.jpg',
      label: 'Lobby A → G Block Corridor Entrance',
      initialYaw: 0,
      forward: { yaw: 0, pitch: 0 },
      back: { yaw: 180, pitch: 0 },
    },
    {
      id: 3,
      image: '/images360/LobbyA_5_Dining.jpg',
      label: 'Connecting Corridor',
      initialYaw: 0,
      forward: { yaw: 0, pitch: 0 },
      back: { yaw: 180, pitch: 0 },
    },
    {
      id: 4,
      image: '/images360/LobbyA_6_Dining.jpg',
      label: 'Corridor Midpoint',
      initialYaw: 190,
      forward: { yaw: 185, pitch: 0 },
      back: { yaw: 359, pitch: 0 },
    },
    {
      id: 5,
      image: '/images360/LobbyA_7_Dining.jpg',
      label: 'G Block Entrance Ahead',
      initialYaw: 220,
      forward: { yaw: 220, pitch: 0 },
      back: { yaw: 0, pitch: 0 },
    },
    {
      id: 6,
      image: '/images360/LobbyA_10_Dining.jpg',
      label: 'G Block Entrance Door',
      initialYaw: 0,
      forward: { yaw: 0, pitch: 0 },
      back: { yaw: 180, pitch: 0 },
    },
    {
      id: 7,
      image: '/images360/LobbyA_11_Dining.jpg',
      label: 'Inside G Block Lobby',
      initialYaw: 0,
      forward: { yaw: 0, pitch: -3 },
      back: { yaw: 180, pitch: -4 },
    },
    {
      id: 8,
      image: '/images360/LobbyA_12_Dining.jpg',
      label: 'Walkway Toward Dining Area',
      initialYaw: 0,
      forward: { yaw: 0, pitch: 0 },
      back: { yaw: 180, pitch: 0 },
    },
    {
      id: 9,
      image: '/images360/LobbyA_13_Dining.jpg',
      label: 'Dining Area First Section',
      initialYaw: 0,
      forward: { yaw: 0, pitch: -3 },
      back: { yaw: 180, pitch: 0 },
    },
    {
      id: 10,
      image: '/images360/LobbyA_17_Dining.jpg',
      label: 'Dining Area Mid Section',
      initialYaw: 0,
      forward: { yaw: 0, pitch: 0 },
      back: { yaw: 180, pitch: 0 },
    },
    {
      id: 11,
      image: '/images360/LobbyA_14_Dining.jpg',
      label: 'Dining Area',
      initialYaw: 0,
      forward: { yaw: 0, pitch: 0 },
      back: { yaw: 180, pitch: 0 },
    },
    {
      id: 12,
      image: '/images360/LobbyA_15_Dining.jpg',
      label: 'Student Hub Entrance Area',
      initialYaw: 0,
      forward: { yaw: 0, pitch: -3 },
      back: { yaw: 180, pitch: 0 },
    },
    {
      id: 13,
      image: '/images360/LobbyA_16_Dining.jpg',
      label: 'Inside Student Hub',
      initialYaw: 0,
      back: { yaw: 180, pitch: 0 },
    },
    {
      id: 14,
      image: '/images360/StudentHub1.jpg',
      label: 'Inside Student Hub',
      initialYaw: 0,
      back: { yaw: 180, pitch: 0 },
    },
  ],
  nextRouteIds: ['borneo-mph', 'mph-borneo'],
};

// Library
export const lobbyLibraryRoute: RouteDefinition = {
  id: 'lobby-hq',
  title: 'Lobby → Library',
  fromNode: 'Block A Lobby',
  toNode: 'Library',
  scenes: [
    {
      id: 1,
      image: '/images360/lobby_c1.jpg',
      label: 'Block A Lobby',
      initialYaw: 180,
      forward: { yaw: 200, pitch: -9 },
    },
    {
      id: 2,
      image: '/images360/lobby_c4.jpg',
      label: 'Use Staircase to go Level 1 Library',
      initialYaw: 100,
      forward: { yaw: 110, pitch: 0 },
      back: { yaw: 330, pitch: 0 },
    },
    {
      id: 3,
      image: '/images360/library_c5.jpg',
      label: 'Go straight to Library Entrance',
      initialYaw: 360,
      forward: { yaw: 355, pitch: 0 },
      back: { yaw: 180, pitch: -30 },
    },
    {
      id: 4,
      image: '/images360/library_c7.jpg',
      label: 'Enter with using Student ID if got.',
      initialYaw: 360,
      forward: { yaw: 355, pitch: 0 },
      back: { yaw: 125, pitch: 0 },
    },
    {
      id: 5,
      image: '/images360/library12.jpg',
      label: 'Library Lobby',
      initialYaw: 30,
      forward: { yaw: 350, pitch: 0 },
      back: { yaw: 65, pitch: 0 },
    },
    {
      id: 6,
      image: '/images360/library_c9.jpg',
      label: 'Quiet Zone',
      initialYaw: 100,
      forward: { yaw: 180, pitch: 0 },
      back: { yaw: 270, pitch: 0 },
    },
    {
      id: 7,
      image: '/images360/library_c10.jpg',
      label: 'Book Section',
      initialYaw: 80,
      back: { yaw: 180, pitch: 0 },
    },
  ],
  nextRouteIds: ['borneo-mph', 'mph-borneo'],
};

// Junction
export const lobbyJunctionRoute: RouteDefinition = {
  id: 'lobby-junction',
  title: 'Lobby → Junction',
  fromNode: 'Block A Lobby',
  toNode: 'Junction',
  scenes: [
    {
      id: 1,
      image: '/images360/L-B-1.jpg',
      label: 'Block A Lobby',
      initialYaw: 20,
      forward: { yaw: 30, pitch: 0 },
    },
    {
      id: 2,
      image: '/images360/L-B-3.jpg',
      label: 'Block A Groundfloor Toilet',
      initialYaw: 175,
      forward: { yaw: 178, pitch: -5 },
      back: { yaw: 70, pitch: -6 },
    },
    {
      id: 3,
      image: '/images360/L-B-6.jpg',
      label: 'Walkway in Corridor',
      initialYaw: 360,
      forward: { yaw: 355, pitch: 0 },
      back: { yaw: 89, pitch: -4 },
    },
    {
      id: 4,
      image: '/images360/L-B-8.jpg',
      label: 'Walkway in Corridor',
      initialYaw: 360,
      forward: { yaw: 355, pitch: 0 },
      back: { yaw: 175, pitch: -4 },
    },
    {
      id: 5,
      image: '/images360/L-B-10.jpg',
      label: 'Go Straight and ready turn left',
      initialYaw: 180,
      forward: { yaw: 165, pitch: -4 },
      back: { yaw: 358, pitch: 0 },
    },
    {
      id: 6,
      image: '/images360/L-B-12.jpg',
      label: 'Leisure Zone',
      initialYaw: 10,
      forward: { yaw: 355, pitch: 0 },
      back: { yaw: 250, pitch: -5 },
    },
    {
      id: 7,
      image: '/images360/L-B-15.jpg',
      label: 'You are almost there',
      initialYaw: 355,
      forward: { yaw: 355, pitch: -10 },
      back: { yaw: 213, pitch: -6 },
    },
    {
      id: 8,
      image: '/images360/L-J-16.jpg',
      label: 'Left side got escalator can go up to Junction',
      initialYaw: 325,
      forward: { yaw: 315, pitch: -10 },
      back: { yaw: 180, pitch: -6 },
    },
    {
      id: 9,
      image: '/images360/L-J-18.jpg',
      label: 'Go up escalator',
      initialYaw: 360,
      forward: { yaw: 360, pitch: 20 },
      back: { yaw: 290, pitch: -12 },
    },
    {
      id: 10,
      image: '/images360/L-J-19.jpg',
      label: 'Junction Balcony',
      initialYaw: 360,
      forward: { yaw: 10, pitch: -12 },
      back: { yaw: 175, pitch: -18 },
    },
    {
      id: 11,
      image: '/images360/L-J-20.jpg',
      label: 'You arrive Junction Level 1',
      initialYaw: 270,
      back: { yaw: 180, pitch: -4 },
    },
  ],
  nextRouteIds: ['borneo-mph', 'mph-borneo'],
};

// HQ
export const lobbyHqRoute: RouteDefinition = {
  id: 'lobby-hq',
  title: 'Lobby → HQ',
  fromNode: 'Block A Lobby',
  toNode: 'HQ',
  scenes: [
    {
      id: 1,
      image: '/images360/lobby_c1.jpg',
      label: 'Block A Lobby',
      initialYaw: 230,
      forward: { yaw: 243, pitch: 0 },
    },
    {
      id: 2,
      image: '/images360/L-H-2.jpg',
      label: 'Student HQ Entrance',
      initialYaw: 0,
      forward: { yaw: 350, pitch: 0 },
      back: { yaw: 140, pitch: 0 },
    },
    {
      id: 3,
      image: '/images360/L-H-3.jpg',
      label: 'Financial Desk Services Area',
      initialYaw: 18,
      forward: { yaw: 55, pitch: 0 },
      back: { yaw: 160, pitch: 0 },
    },
    {
      id: 4,
      image: '/images360/L-H-4.jpg',
      label: 'Student HQ Lobby',
      initialYaw: 340,
      back: { yaw: 250, pitch: 0 },
    },
  ],
  nextRouteIds: ['borneo-mph', 'mph-borneo'],
};

// G Block
export const lobbyGblockRoute: RouteDefinition = {
  id: 'lobby-gblock',
  title: 'Lobby → G Block',
  fromNode: 'Block A Lobby',
  toNode: 'G Block',
  scenes: [
    {
      id: 1,
      image: '/images360/LobbyA_1_Dining.jpg',
      label: 'A Block Lobby',
      initialYaw: 0,
      forward: { yaw: 0, pitch: 0 },
    },
    {
      id: 2,
      image: '/images360/LobbyA_3_Dining.jpg',
      label: 'Lobby A → G Block Corridor Entrance',
      initialYaw: 0,
      forward: { yaw: 0, pitch: 0 },
      back: { yaw: 180, pitch: 0 },
    },
    {
      id: 3,
      image: '/images360/LobbyA_5_Dining.jpg',
      label: 'Connecting Corridor',
      initialYaw: 0,
      forward: { yaw: 0, pitch: 0 },
      back: { yaw: 180, pitch: 0 },
    },
    {
      id: 4,
      image: '/images360/LobbyA_6_Dining.jpg',
      label: 'Corridor Midpoint',
      initialYaw: 180,
      forward: { yaw: 180, pitch: 0 },
      back: { yaw: 0, pitch: 0 },
    },
    {
      id: 5,
      image: '/images360/LobbyA_7_Dining.jpg',
      label: 'G Block Entrance Ahead',
      initialYaw: 220,
      forward: { yaw: 220, pitch: 0 },
      back: { yaw: 0, pitch: 0 },
    },
    {
      id: 6,
      image: '/images360/LobbyA_11_Dining.jpg',
      label: 'G Block Entrance Door',
      initialYaw: 0,
      forward: { yaw: 0, pitch: 0 },
    },
  ],
  nextRouteIds: ['borneo-mph', 'mph-borneo'],
};

//  Student Village
export const lobbySvRoute: RouteDefinition = {
  id: 'lobby-SV',
  title: 'Lobby → Student Village',
  fromNode: 'Block A Lobby',
  toNode: 'Student Village',
  scenes: [
    {
      id: 1,
      image: '/images360/LobbyA_1_Dining.jpg',
      label: 'A Block Lobby',
      initialYaw: 0,
      forward: { yaw: 0, pitch: 0 },
    },
    {
      id: 2,
      image: '/images360/LobbyA_3_Dining.jpg',
      label: 'Lobby A → G Block Corridor Entrance',
      initialYaw: 0,
      forward: { yaw: 0, pitch: 0 },
      back: { yaw: 180, pitch: 0 },
    },
    {
      id: 3,
      image: '/images360/LobbyA_5_Dining.jpg',
      label: 'Connecting Corridor',
      initialYaw: 0,
      forward: { yaw: 0, pitch: 0 },
      back: { yaw: 180, pitch: 0 },
    },
    {
      id: 4,
      image: '/images360/LobbyA_6_Dining.jpg',
      label: 'Corridor Midpoint',
      initialYaw: 190,
      forward: { yaw: 185, pitch: 0 },
      back: { yaw: 359, pitch: 0 },
    },
    {
      id: 5,
      image: '/images360/LobbyA_7_Dining.jpg',
      label: 'G Block Entrance Ahead',
      initialYaw: 220,
      forward: { yaw: 220, pitch: 0 },
      back: { yaw: 0, pitch: 0 },
    },
    {
      id: 6,
      image: '/images360/LobbyA_10_Dining.jpg',
      label: 'G Block Entrance Door',
      initialYaw: 0,
      forward: { yaw: 0, pitch: 0 },
      back: { yaw: 180, pitch: 0 },
    },
    {
      id: 7,
      image: '/images360/LobbyA_11_Dining.jpg',
      label: 'Inside G Block Lobby',
      initialYaw: 0,
      forward: { yaw: 0, pitch: -3 },
      back: { yaw: 180, pitch: -4 },
    },
    {
      id: 8,
      image: '/images360/LobbyA_12_Dining.jpg',
      label: 'Walkway Toward Dining Area',
      initialYaw: 0,
      forward: { yaw: 0, pitch: 0 },
      back: { yaw: 180, pitch: 0 },
    },
    {
      id: 9,
      image: '/images360/LobbyA_13_Dining.jpg',
      label: 'Dining Area First Section',
      initialYaw: 0,
      forward: { yaw: 0, pitch: -3 },
      back: { yaw: 180, pitch: 0 },
    },
    {
      id: 10,
      image: '/images360/LobbyA_17_Dining.jpg',
      label: 'Dining Area Mid Section',
      initialYaw: 0,
      forward: { yaw: 0, pitch: 0 },
      back: { yaw: 180, pitch: 0 },
    },
    {
      id: 11,
      image: '/images360/LobbyA_14_Dining.jpg',
      label: 'Dining Area',
      initialYaw: 0,
      forward: { yaw: 0, pitch: 0 },
      back: { yaw: 180, pitch: 0 },
    },
    {
      id: 12,
      image: '/images360/sv-shub1.jpg',
      label: 'Student Hub Entrance Area',
      initialYaw: 270,
      forward: { yaw: 280, pitch: -3 },
      back: { yaw: 190, pitch: 0 },
    },
    {
      id: 13,
      image: '/images360/sv-shub2.jpg',
      label: 'Inside Student Hub',
      initialYaw: 180,
      forward: { yaw: 190, pitch: -2 },
      back: { yaw: 20, pitch: 0 },
    },
    {
      id: 14,
      image: '/images360/sv-shub3.jpg',
      label: 'Inside Student Hub',
      initialYaw: 180,
      forward: { yaw: 160, pitch: -2 },
      back: { yaw: 0, pitch: 0 },
    },
    {
      id: 15,
      image: '/images360/sv-shub4.jpg',
      label: 'Inside Student Hub',
      initialYaw: 180,
      forward: { yaw: 180, pitch: 0 },
      back: { yaw: 0, pitch: 0 },
    },
    {
      id: 16,
      image: '/images360/sv-shub5.jpg',
      label: 'Inside Student Hub',
      initialYaw: 180,
      forward: { yaw: 180, pitch: 0 },
      back: { yaw: 0, pitch: 0 },
    },
    {
      id: 17,
      image: '/images360/sv_outside.jpg',
      label: 'Inside Student Hub',
      initialYaw: 0,
    },
  ],
  // nextRouteIds: ['...', '...'],
};

