// import type { RouteDefinition } from './types';

// export const lobbyDiningRoute: RouteDefinition = {
//   id: 'lobby-dining',
//   title: 'Lobby → Dining Hall',
//   fromNode: 'Block A Lobby',
//   toNode: 'Dining Hall',
//   scenes: [
//     {
//       id: 1,
//       image: '/images360/LobbyA_1_Dining.jpg',
//       label: 'A Block Lobby',
//       initialYaw: 0,
//       forward: { yaw: 0, pitch: 0 },
//       instruction: 'You are now at Lobby A. Move forward along the walkway.',
//     },
//     {
//       id: 2,
//       image: '/images360/LobbyA_3_Dining.jpg',
//       label: 'Lobby A → G Block Corridor Entrance',
//       initialYaw: 0,
//       forward: { yaw: 0, pitch: 0 },
//       back: { yaw: 180, pitch: 0 },
//       instruction: 'Continue straight through the corridor leading toward G Block.',
//     },
//     {
//       id: 3,
//       image: '/images360/LobbyA_5_Dining.jpg',
//       label: 'Connecting Corridor',
//       initialYaw: 0,
//       forward: { yaw: 0, pitch: 0 },
//       back: { yaw: 180, pitch: 0 },
//       instruction: 'Keep walking straight along the corridor.',
//     },
//     {
//       id: 4,
//       image: '/images360/LobbyA_6_Dining.jpg',
//       label: 'Corridor Midpoint',
//       initialYaw: 190,
//       forward: { yaw: 185, pitch: 0 },
//       back: { yaw: 359, pitch: 0 },
//       instruction: 'Continue heading straight toward G Block.',
//     },
//     {
//       id: 5,
//       image: '/images360/LobbyA_7_Dining.jpg',
//       label: 'G Block Entrance Ahead',
//       initialYaw: 220,
//       forward: { yaw: 220, pitch: 0 },
//       back: { yaw: 0, pitch: 0 },
//       instruction: 'Turn right here and enter the G Block building.',
//     },
//     {
//       id: 6,
//       image: '/images360/LobbyA_10_Dining.jpg',
//       label: 'G Block Entrance Door',
//       initialYaw: 0,
//       forward: { yaw: 0, pitch: 0 },
//       back: { yaw: 180, pitch: 0 },
//       instruction: 'Go straight and enter through the G Block door.',
//     },
//     {
//       id: 7,
//       image: '/images360/LobbyA_11_Dining.jpg',
//       label: 'Inside G Block Lobby',
//       initialYaw: 0,
//       forward: { yaw: 0, pitch: -3 },
//       back: { yaw: 180, pitch: -4 },
//       instruction: 'You have entered G Block. The service desk is on your left. Continue walking straight.',
//     },
//     {
//       id: 8,
//       image: '/images360/LobbyA_12_Dining.jpg',
//       label: 'Walkway Toward Dining Area',
//       initialYaw: 0,
//       forward: { yaw: 0, pitch: 0 },
//       back: { yaw: 180, pitch: 0 },
//       instruction: 'Keep going straight along the walkway.',
//     },
//     {
//       id: 9,
//       image: '/images360/LobbyA_13_Dining.jpg',
//       label: 'Dining Area First Section',
//       initialYaw: 0,
//       forward: { yaw: 0, pitch: -3 },
//       instruction: 'You are now entering the dining area. Continue walking straight ahead.',
//     },

//   ],
//   nextRouteIds: ['borneo-mph', 'mph-borneo'],
// };