import type { RouteDefinition } from './types';

export const mphLibraryRoute: RouteDefinition = {
  id: 'mph-library',
  title: 'MPH → Library',
  fromNode: 'Multi Purpose Hall',
  toNode: 'Library',
  scenes: [
            {
                id: 1,
                image: '/images360/L-M-17.jpg',
                label: 'Multi Purpose Hall Lobby',
                initialYaw: 165,
                forward : { yaw: 165, pitch: -4 },
            },
            {
                id: 2,
                image: '/images360/L-M-16.jpg',
                label: 'Enter the MPH Door',
                initialYaw: 90,
                back : { yaw: 360, pitch: 0 },
                forward: { yaw: 87, pitch: -5 },
            },
            {
                id: 3,
                image: '/images360/L-M-13.jpg',
                label: 'Ready to turn right into MPH',
                initialYaw: 180,
                back : { yaw: 360, pitch: 0 },
                forward: { yaw: 175, pitch: -5 },
            },
            {
                id: 4,
                image: '/images360/L-M-10.jpg',
                label: 'Go Straight',
                initialYaw: 180,
                back : { yaw: 353, pitch: 0 },
                forward: { yaw: 190, pitch: -4 },
            },
            {
                id: 5,
                image: '/images360/L-M-7.jpg',
                label: 'Towards MPH',
                initialYaw: 70,
                back : { yaw: 235, pitch: 0 },
                forward : { yaw: 90, pitch: 0 },
            },
            {
                id: 6,
                image: '/images360/L-B-1.jpg',
                label: 'Block A Lobby',
                initialYaw: 352,
                forward: { yaw: 320, pitch: 0 },
                back: { yaw: 190, pitch: -3 },
            },
            {
                id: 7,
                image: '/images360/lobby_c4.jpg',
                label: 'Use Staircase to go Level 1 Library',
                initialYaw: 100,
                forward: { yaw: 110, pitch: 0 },
                back: { yaw: 330, pitch: 0 },
            },
            {
                id: 8,
                image: '/images360/library_c5.jpg',
                label: 'Go straight to Library Entrance',
                initialYaw: 360,
                forward: { yaw: 355, pitch: 0 },
                back: { yaw: 180, pitch: -30 },
            },
            {
                id: 9,
                image: '/images360/library_c7.jpg',
                label: 'Enter with using Student ID if got.',
                initialYaw: 360,
                forward: { yaw: 355, pitch: 0 },
                back: { yaw: 125, pitch: 0 },
            },
            {
                id: 10,
                image: '/images360/library12.jpg',
                label: 'Library Lobby',
                initialYaw: 30,
                forward: { yaw: 350, pitch: 0 },
                back: { yaw: 65, pitch: 0 },
            },
            {
                id: 11,
                image: '/images360/library_c9.jpg',
                label: 'Quiet Zone',
                initialYaw: 100,
                forward: { yaw: 180, pitch: 0 },
                back: { yaw: 270, pitch: 0 },
            },
            {
                id: 12,
                image: '/images360/library_c10.jpg',
                label: 'Book Section',
                initialYaw: 80,
            },
  ],
};

export const mphJunctionRoute: RouteDefinition = {
  id: 'mph-junction',
  title: 'MPH → Junction',
  fromNode: 'Multi Purpose Hall',
  toNode: 'Junction',
  scenes: [
            {
                id: 1,
                image: '/images360/L-M-17.jpg',
                label: 'Multi Purpose Hall Lobby',
                initialYaw: 165,
                forward : { yaw: 165, pitch: -4 },
            },
            {
                id: 2,
                image: '/images360/L-M-16.jpg',
                label: 'Enter the MPH Door',
                initialYaw: 90,
                back : { yaw: 360, pitch: 0 },
                forward: { yaw: 87, pitch: -5 },
            },
            {
                id: 3,
                image: '/images360/L-M-13.jpg',
                label: 'Ready to turn right into MPH',
                initialYaw: 180,
                back : { yaw: 360, pitch: 0 },
                forward: { yaw: 175, pitch: -5 },
            },
            {
                id: 4,
                image: '/images360/L-M-10.jpg',
                label: 'Go Straight',
                initialYaw: 180,
                back : { yaw: 353, pitch: 0 },
                forward: { yaw: 190, pitch: -4 },
            },
            {
                id: 5,
                image: '/images360/L-M-7.jpg',
                label: 'Towards MPH',
                initialYaw: 70,
                back : { yaw: 235, pitch: 0 },
                forward : { yaw: 90, pitch: 0 },
            },
            {
                id: 7,
                image: '/images360/L-B-1.jpg',
                label: 'Block A Lobby',
                initialYaw: 20,
                forward: { yaw: 30, pitch: 0 },
            },
            {
                id: 8,
                image: '/images360/L-B-3.jpg',
                label: 'Block A Groundfloor Toilet',
                initialYaw: 175,
                forward: { yaw: 178, pitch: -5 },
                back: { yaw: 70, pitch: -6 },
            },
            {
                id: 9,
                image: '/images360/L-B-6.jpg',
                label: 'Walkway in Corridor',
                initialYaw: 360,
                forward: { yaw: 355, pitch: 0 },
                back: { yaw: 89, pitch: -4 },
            },
            {
                id: 10,
                image: '/images360/L-B-8.jpg',
                label: 'Walkway in Corridor',
                initialYaw: 360,
                forward: { yaw: 355, pitch: 0 },
                back: { yaw: 175, pitch: -4 },
            },
            {
                id: 11,
                image: '/images360/L-B-10.jpg',
                label: 'Go Straight and ready turn left',
                initialYaw: 180,
                forward: { yaw: 165, pitch: -4 },
                back: { yaw: 358, pitch: 0 },
            },
            {
                id: 12,
                image: '/images360/L-B-12.jpg',
                label: 'Leisure Zone',
                initialYaw: 10,
                forward: { yaw: 355, pitch: 0 },
                back: { yaw: 250, pitch: -5 },
            },
            {
                id: 13,
                image: '/images360/L-B-15.jpg',
                label: 'You are almost there',
                initialYaw: 355,
                forward: { yaw: 330, pitch: 0 },
                back: { yaw: 213, pitch: -6 },
            },
            {
                id: 14,
                image: '/images360/L-J-18.jpg',
                label: 'Go up escalator',
                initialYaw: 360,
                forward: { yaw: 360, pitch: 20 },
                back: { yaw: 290, pitch: -12 },
            },
            {
                id: 15,
                image: '/images360/L-J-19.jpg',
                label: 'Junction Balcony',
                initialYaw: 360,
                forward: { yaw: 10, pitch: -12 },
                back: { yaw: 175, pitch: -18 },
            },
            {
                id: 16,
                image: '/images360/L-J-20.jpg',
                label: 'You arrive Junction Level 1',
                initialYaw: 270,
            },
  ],
};

export const mphBorneoRoute: RouteDefinition = {
  id: 'mph-borneo',
  title: 'MPH → Borneo Atrium',
  fromNode: 'Multi Purpose Hall',
  toNode: 'Borneo Atrium',
  scenes: [
            {
                id: 1,
                image: '/images360/L-M-17.jpg',
                label: 'Multi Purpose Hall Lobby',
                initialYaw: 165,
                forward : { yaw: 165, pitch: -4 },
            },
            {
                id: 2,
                image: '/images360/L-M-16.jpg',
                label: 'Enter the MPH Door',
                initialYaw: 90,
                back : { yaw: 360, pitch: 0 },
                forward: { yaw: 87, pitch: -5 },
            },
            {
                id: 3,
                image: '/images360/L-M-13.jpg',
                label: 'Ready to turn right into MPH',
                initialYaw: 180,
                back : { yaw: 360, pitch: 0 },
                forward: { yaw: 175, pitch: -5 },
            },
            {
                id: 4,
                image: '/images360/L-M-10.jpg',
                label: 'Go Straight',
                initialYaw: 180,
                back : { yaw: 353, pitch: 0 },
                forward: { yaw: 190, pitch: -4 },
            },
            {
                id: 5,
                image: '/images360/L-M-7.jpg',
                label: 'Towards MPH',
                initialYaw: 70,
                back : { yaw: 235, pitch: 0 },
                forward : { yaw: 90, pitch: 0 },
            },
            {
                id: 6,
                image: '/images360/L-B-1.jpg',
                label: 'Block A Lobby',
                initialYaw: 20,
                forward: { yaw: 30, pitch: 0 },
            },
            {
                id: 7,
                image: '/images360/L-B-3.jpg',
                label: 'Block A Groundfloor Toilet',
                initialYaw: 175,
                forward: { yaw: 178, pitch: -5 },
                back: { yaw: 70, pitch: -6 },
            },
            {
                id: 8,
                image: '/images360/L-B-6.jpg',
                label: 'Walkway in Corridor',
                initialYaw: 360,
                forward: { yaw: 355, pitch: 0 },
                back: { yaw: 89, pitch: -4 },
            },
            {
                id: 9,
                image: '/images360/L-B-8.jpg',
                label: 'Walkway in Corridor',
                initialYaw: 360,
                forward: { yaw: 355, pitch: 0 },
                back: { yaw: 175, pitch: -4 },
            },
            {
                id: 10,
                image: '/images360/L-B-10.jpg',
                label: 'Go Straight and ready turn left',
                initialYaw: 180,
                forward: { yaw: 165, pitch: -4 },
                back: { yaw: 358, pitch: 0 },
            },
            {
                id: 11,
                image: '/images360/L-B-12.jpg',
                label: 'Leisure Zone',
                initialYaw: 10,
                forward: { yaw: 355, pitch: 0 },
                back: { yaw: 250, pitch: -5 },
            },
            {
                id: 12,
                image: '/images360/L-B-15.jpg',
                label: 'You are almost there',
                initialYaw: 355,
                forward: { yaw: 355, pitch: 0 },
                back: { yaw: 213, pitch: -6 },
            },
            {
                id: 13,
                image: '/images360/L-B-16.jpg',
                label: 'Left side got escalator can go up to Junction',
                initialYaw: 355,
                forward: { yaw: 10, pitch: 0 },
                back: { yaw: 180, pitch: -5 },
            },
            {
                id: 14,
                image: '/images360/L-B-18.jpg',
                label: 'You arrive the Borneo Atrium! Welcome!',
                initialYaw: 180,
            },
  ],
};

export const mphSvRoute: RouteDefinition = {
  id: 'mph-SV',
  title: 'MPH → Student Village',
  fromNode: 'MPH',
  toNode: 'Student Village',
  scenes: [
            {
                id: 1,
                image: '/images360/L-B-18.jpg',
                label: 'You arrive the Borneo Atrium! Welcome!',
                initialYaw: 180,
                forward: { yaw: 190, pitch: -7 },
            },
            {
                id: 2,
                image: '/images360/L-B-16.jpg',
                label: 'Left side got escalator can go up to Junction',
                initialYaw: 175,
                back : { yaw: 10, pitch: 0 },
                forward : { yaw: 180, pitch: -5 },
            },
  ],
};

export const mphHQRoute: RouteDefinition = {
  id: 'mph-hq',
  title: 'MPH → HQ',
  fromNode: 'MPH',
  toNode: 'HQ',
  scenes: [
            {
                id: 1,
                image: '/images360/L-B-18.jpg',
                label: 'You arrive the Borneo Atrium! Welcome!',
                initialYaw: 180,
                forward: { yaw: 190, pitch: -7 },
            },
            {
                id: 2,
                image: '/images360/L-B-16.jpg',
                label: 'Left side got escalator can go up to Junction',
                initialYaw: 175,
                back : { yaw: 10, pitch: 0 },
                forward : { yaw: 180, pitch: -5 },
            },
  ],
};

export const mphDiningRoute: RouteDefinition = {
  id: 'mph-dining',
  title: 'MPH → Dining Hall',
  fromNode: 'MPH',
  toNode: 'Dining Hall',
  scenes: [
            {
                id: 1,
                image: '/images360/L-B-18.jpg',
                label: 'You arrive the Borneo Atrium! Welcome!',
                initialYaw: 180,
                forward: { yaw: 190, pitch: -7 },
            },
            {
                id: 2,
                image: '/images360/L-J-18.jpg',
                label: 'Go up escalator',
                initialYaw: 360,
                forward: { yaw: 360, pitch: 20 },
                back: { yaw: 290, pitch: -12 },
            },
    ],
};

export const mphGblockRoute: RouteDefinition = {
  id: 'mph-gblock',
  title: 'MPH → G Block',
  fromNode: 'MPH',
  toNode: ' G Block',
  scenes: [
    {
        id: 1,
        image: '/images360/L-B-18.jpg',
        label: 'Borneo Atrium Entrance',
        initialYaw: 180,
        forward: { yaw: 225, pitch: -7 },
    },
    {
        id: 2,
        image: '/images360/L-J-18.jpg',
        label: 'Escalator to Junction Level 1',
        initialYaw: 360,
        forward: { yaw: 360, pitch: 20 },
        back: { yaw: 290, pitch: -12 },
    },
  ],
};

export const mphShubRoute: RouteDefinition = {
  id: 'mph-shub',
  title: 'MPH → Student Hub',
  fromNode: 'MPH',
  toNode: 'Student Hub',
  scenes: [
    {
        id: 1,
        image: '/images360/L-B-18.jpg',
        label: 'Borneo Atrium Entrance',
        initialYaw: 180,
        forward: { yaw: 225, pitch: -7 },
    },
    {
        id: 2,
        image: '/images360/L-J-18.jpg',
        label: 'Escalator to Junction Level 1',
        initialYaw: 360,
        forward: { yaw: 360, pitch: 20 },
        back: { yaw: 290, pitch: -12 },
    },
  ],
};

export const borneoRoutes = {
  'mph-library': mphLibraryRoute,
  'mph-junction': mphJunctionRoute,
  'mph-borneo': mphBorneoRoute,
  'mph-SV': mphSvRoute,
  'mph-hq': mphHQRoute,
  'mph-dining':mphDiningRoute,
  'mph-gblock': mphGblockRoute,
  'mph-shub': mphShubRoute,
};