import type { RouteDefinition } from './types';

export const mphLibraryRoute: RouteDefinition = {
  id: 'mph-library',
  title: 'MPH → Library',
  fromNode: 'Multi Purpose Hall',
  toNode: 'Library',
  scenes: [
            {
                id: 1,
                image: '/images360/L-M-17.jpg',
                label: 'Multi Purpose Hall Lobby',
                initialYaw: 165,
                forward : { yaw: 165, pitch: -4 },
            },
            {
                id: 2,
                image: '/images360/L-M-16.jpg',
                label: 'Go out MPH Door',
                initialYaw: 90,
                back : { yaw: 360, pitch: 0 },
                forward: { yaw: 87, pitch: -5 },
            },
            {
                id: 3,
                image: '/images360/L-M-13.jpg',
                label: 'Go Straight',
                initialYaw: 180,
                back : { yaw: 360, pitch: 0 },
                forward: { yaw: 175, pitch: -5 },
            },
            {
                id: 4,
                image: '/images360/L-M-10.jpg',
                label: 'Go Forward',
                initialYaw: 180,
                back : { yaw: 353, pitch: 0 },
                forward: { yaw: 190, pitch: -4 },
            },
            {
                id: 5,
                image: '/images360/L-M-7.jpg',
                label: 'Go toward Block A',
                initialYaw: 70,
                back : { yaw: 235, pitch: 0 },
                forward : { yaw: 90, pitch: 0 },
            },
            {
                id: 6,
                image: '/images360/L-B-1.jpg',
                label: 'Block A Lobby',
                initialYaw: 352,
                forward: { yaw: 320, pitch: 0 },
                back: { yaw: 190, pitch: -3 },
            },
            {
                id: 7,
                image: '/images360/lobby_c4.jpg',
                label: 'Use Staircase to go Level 1 Library',
                initialYaw: 100,
                forward: { yaw: 110, pitch: 0 },
                back: { yaw: 330, pitch: 0 },
            },
            {
                id: 8,
                image: '/images360/library_c5.jpg',
                label: 'Go straight to Library Entrance',
                initialYaw: 360,
                forward: { yaw: 355, pitch: 0 },
                back: { yaw: 180, pitch: -30 },
            },
            {
                id: 9,
                image: '/images360/library_c7.jpg',
                label: 'Enter with using Student ID if got.',
                initialYaw: 360,
                forward: { yaw: 355, pitch: 0 },
                back: { yaw: 125, pitch: 0 },
            },
            {
                id: 10,
                image: '/images360/library12.jpg',
                label: 'Library Lobby',
                initialYaw: 30,
                forward: { yaw: 350, pitch: 0 },
                back: { yaw: 65, pitch: 0 },
            },
            {
                id: 11,
                image: '/images360/library_c9.jpg',
                label: 'Quiet Zone',
                initialYaw: 100,
                forward: { yaw: 180, pitch: 0 },
                back: { yaw: 270, pitch: 0 },
            },
            {
                id: 12,
                image: '/images360/library_c10.jpg',
                label: 'Book Section',
                initialYaw: 80,
            },
  ],
};

export const mphJunctionRoute: RouteDefinition = {
  id: 'mph-junction',
  title: 'MPH → Junction',
  fromNode: 'Multi Purpose Hall',
  toNode: 'Junction',
  scenes: [
            {
                id: 1,
                image: '/images360/L-M-17.jpg',
                label: 'Multi Purpose Hall Lobby',
                initialYaw: 165,
                forward : { yaw: 165, pitch: -4 },
            },
            {
                id: 2,
                image: '/images360/L-M-16.jpg',
                label: 'Go out MPH Door',
                initialYaw: 90,
                back : { yaw: 360, pitch: 0 },
                forward: { yaw: 87, pitch: -5 },
            },
            {
                id: 3,
                image: '/images360/L-M-13.jpg',
                label: 'Go Straight',
                initialYaw: 180,
                back : { yaw: 360, pitch: 0 },
                forward: { yaw: 175, pitch: -5 },
            },
            {
                id: 4,
                image: '/images360/L-M-10.jpg',
                label: 'Go Straight',
                initialYaw: 180,
                back : { yaw: 353, pitch: 0 },
                forward: { yaw: 190, pitch: -4 },
            },
            {
                id: 5,
                image: '/images360/L-M-7.jpg',
                label: 'Enter Block A',
                initialYaw: 70,
                back : { yaw: 235, pitch: 0 },
                forward : { yaw: 90, pitch: 0 },
            },
            {
                id: 7,
                image: '/images360/L-B-1.jpg',
                label: 'Block A Lobby',
                initialYaw: 20,
                forward: { yaw: 30, pitch: 0 },
            },
            {
                id: 8,
                image: '/images360/L-B-3.jpg',
                label: 'Block A Groundfloor Toilet',
                initialYaw: 175,
                forward: { yaw: 178, pitch: -5 },
                back: { yaw: 70, pitch: -6 },
            },
            {
                id: 9,
                image: '/images360/L-B-6.jpg',
                label: 'Walkway in Corridor',
                initialYaw: 360,
                forward: { yaw: 355, pitch: 0 },
                back: { yaw: 89, pitch: -4 },
            },
            {
                id: 10,
                image: '/images360/L-B-8.jpg',
                label: 'Walkway in Corridor',
                initialYaw: 360,
                forward: { yaw: 355, pitch: 0 },
                back: { yaw: 175, pitch: -4 },
            },
            {
                id: 11,
                image: '/images360/L-B-10.jpg',
                label: 'Go Straight and ready turn left',
                initialYaw: 180,
                forward: { yaw: 165, pitch: -4 },
                back: { yaw: 358, pitch: 0 },
            },
            {
                id: 12,
                image: '/images360/L-B-12.jpg',
                label: 'Leisure Zone',
                initialYaw: 10,
                forward: { yaw: 355, pitch: 0 },
                back: { yaw: 250, pitch: -5 },
            },
            {
                id: 13,
                image: '/images360/L-B-15.jpg',
                label: 'You are almost there',
                initialYaw: 355,
                forward: { yaw: 330, pitch: 0 },
                back: { yaw: 213, pitch: -6 },
            },
            {
                id: 14,
                image: '/images360/L-J-18.jpg',
                label: 'Go up escalator',
                initialYaw: 360,
                forward: { yaw: 360, pitch: 20 },
                back: { yaw: 290, pitch: -12 },
            },
            {
                id: 15,
                image: '/images360/L-J-19.jpg',
                label: 'Junction Balcony',
                initialYaw: 360,
                forward: { yaw: 10, pitch: -12 },
                back: { yaw: 175, pitch: -18 },
            },
            {
                id: 16,
                image: '/images360/L-J-20.jpg',
                label: 'You arrive Junction Level 1',
                initialYaw: 270,
            },
  ],
};

export const mphBorneoRoute: RouteDefinition = {
  id: 'mph-borneo',
  title: 'MPH → Borneo Atrium',
  fromNode: 'Multi Purpose Hall',
  toNode: 'Borneo Atrium',
  scenes: [
            {
                id: 1,
                image: '/images360/L-M-17.jpg',
                label: 'Multi Purpose Hall Lobby',
                initialYaw: 165,
                forward : { yaw: 165, pitch: -4 },
            },
            {
                id: 2,
                image: '/images360/L-M-16.jpg',
                label: 'Go out MPH Door',
                initialYaw: 90,
                back : { yaw: 360, pitch: 0 },
                forward: { yaw: 87, pitch: -5 },
            },
            {
                id: 3,
                image: '/images360/L-M-13.jpg',
                label: 'Go Straight',
                initialYaw: 180,
                back : { yaw: 360, pitch: 0 },
                forward: { yaw: 175, pitch: -5 },
            },
            {
                id: 4,
                image: '/images360/L-M-10.jpg',
                label: 'Go Forward',
                initialYaw: 180,
                back : { yaw: 353, pitch: 0 },
                forward: { yaw: 190, pitch: -4 },
            },
            {
                id: 5,
                image: '/images360/L-M-7.jpg',
                label: 'Towards Block A Lobby',
                initialYaw: 70,
                back : { yaw: 235, pitch: 0 },
                forward : { yaw: 90, pitch: 0 },
            },
            {
                id: 6,
                image: '/images360/L-B-1.jpg',
                label: 'Block A Lobby',
                initialYaw: 20,
                forward: { yaw: 30, pitch: 0 },
            },
            {
                id: 7,
                image: '/images360/L-B-3.jpg',
                label: 'Block A Groundfloor Toilet',
                initialYaw: 175,
                forward: { yaw: 178, pitch: -5 },
                back: { yaw: 70, pitch: -6 },
            },
            {
                id: 8,
                image: '/images360/L-B-6.jpg',
                label: 'Walkway in Corridor',
                initialYaw: 360,
                forward: { yaw: 355, pitch: 0 },
                back: { yaw: 89, pitch: -4 },
            },
            {
                id: 9,
                image: '/images360/L-B-8.jpg',
                label: 'Walkway in Corridor',
                initialYaw: 360,
                forward: { yaw: 355, pitch: 0 },
                back: { yaw: 175, pitch: -4 },
            },
            {
                id: 10,
                image: '/images360/L-B-10.jpg',
                label: 'Go Straight and ready turn left',
                initialYaw: 180,
                forward: { yaw: 165, pitch: -4 },
                back: { yaw: 358, pitch: 0 },
            },
            {
                id: 11,
                image: '/images360/L-B-12.jpg',
                label: 'Leisure Zone',
                initialYaw: 10,
                forward: { yaw: 355, pitch: 0 },
                back: { yaw: 250, pitch: -5 },
            },
            {
                id: 12,
                image: '/images360/L-B-15.jpg',
                label: 'You are almost there',
                initialYaw: 355,
                forward: { yaw: 355, pitch: 0 },
                back: { yaw: 213, pitch: -6 },
            },
            {
                id: 13,
                image: '/images360/L-B-16.jpg',
                label: 'Left side got escalator can go up to Junction',
                initialYaw: 355,
                forward: { yaw: 10, pitch: 0 },
                back: { yaw: 180, pitch: -5 },
            },
            {
                id: 14,
                image: '/images360/L-B-18.jpg',
                label: 'You arrive the Borneo Atrium! Welcome!',
                initialYaw: 180,
            },
  ],
};

export const mphSvRoute: RouteDefinition = {
  id: 'mph-SV',
  title: 'MPH → Student Village',
  fromNode: 'MPH',
  toNode: 'Student Village',
  scenes: [
            {
                id: 1,
                image: '/images360/L-M-17.jpg',
                label: 'Multi Purpose Hall Lobby',
                initialYaw: 165,
                forward : { yaw: 165, pitch: -4 },
            },
            {
                id: 2,
                image: '/images360/L-M-16.jpg',
                label: 'Go out MPH Door',
                initialYaw: 90,
                back : { yaw: 360, pitch: 0 },
                forward: { yaw: 87, pitch: -5 },
            },
            {
                id: 3,
                image: '/images360/L-M-13.jpg',
                label: 'Go Straight',
                initialYaw: 180,
                back : { yaw: 360, pitch: 0 },
                forward: { yaw: 175, pitch: -5 },
            },
            {
                id: 4,
                image: '/images360/L-M-10.jpg',
                label: 'Go Straight',
                initialYaw: 180,
                back : { yaw: 353, pitch: 0 },
                forward: { yaw: 190, pitch: -4 },
            },
            {
                id: 5,
                image: '/images360/L-M-7.jpg',
                label: 'Enter Block A',
                initialYaw: 70,
                back : { yaw: 235, pitch: 0 },
                forward : { yaw: 90, pitch: 0 },
            },
            {
                id: 6,
                image: '/images360/LobbyA_1_Dining.jpg',
                label: 'A Block Lobby',
                initialYaw: 20,
                forward: { yaw: 0, pitch: 0 },
                back : { yaw: 235, pitch: 0 },
            },
            {
                id: 7,
                image: '/images360/LobbyA_3_Dining.jpg',
                label: 'Lobby A → G Block Corridor Entrance',
                initialYaw: 0,
                forward: { yaw: 0, pitch: 0 },
                back: { yaw: 200, pitch: -7 },
            },
            {
                id: 8,
                image: '/images360/LobbyA_5_Dining.jpg',
                label: 'Connecting Corridor',
                initialYaw: 0,
                forward: { yaw: 0, pitch: 0 },
                back: { yaw: 180, pitch: 0 },
            },
            {
                id: 9,
                image: '/images360/LobbyA_6_Dining.jpg',
                label: 'Corridor Midpoint',
                initialYaw: 190,
                forward: { yaw: 185, pitch: 0 },
                back: { yaw: 359, pitch: 0 },
            },
            {
                id: 10,
                image: '/images360/LobbyA_7_Dining.jpg',
                label: 'G Block Entrance Ahead',
                initialYaw: 220,
                forward: { yaw: 220, pitch: 0 },
                back: { yaw: 0, pitch: 0 },
            },
            {
                id: 11,
                image: '/images360/LobbyA_10_Dining.jpg',
                label: 'G Block Entrance Door',
                initialYaw: 0,
                forward: { yaw: 0, pitch: 0 },
                back: { yaw: 180, pitch: 0 },
            },
            {
                id: 12,
                image: '/images360/LobbyA_11_Dining.jpg',
                label: 'Inside G Block Lobby',
                initialYaw: 0,
                forward: { yaw: 0, pitch: -3 },
                back: { yaw: 180, pitch: -4 },
            },
            {
                id: 13,
                image: '/images360/LobbyA_12_Dining.jpg',
                label: 'Walkway Toward Dining Area',
                initialYaw: 0,
                forward: { yaw: 0, pitch: 0 },
                back: { yaw: 180, pitch: 0 },
            },
            {
                id: 14,
                image: '/images360/LobbyA_13_Dining.jpg',
                label: 'Dining Area First Section',
                initialYaw: 0,
                forward: { yaw: 0, pitch: -3 },
                back: { yaw: 180, pitch: 0 },
            },
            {
                id: 15,
                image: '/images360/LobbyA_17_Dining.jpg',
                label: 'Dining Area Mid Section',
                initialYaw: 0,
                forward: { yaw: 0, pitch: 0 },
                back: { yaw: 180, pitch: 0 },
            },
            {
                id: 16,
                image: '/images360/LobbyA_14_Dining.jpg',
                label: 'Dining Area',
                initialYaw: 0,
                forward: { yaw: 0, pitch: 0 },
                back: { yaw: 180, pitch: 0 },
            },
            {
                id: 17,
                image: '/images360/sv-shub1.jpg',
                label: 'Student Hub Entrance Area',
                initialYaw: 270,
                forward: { yaw: 280, pitch: -3 },
                back: { yaw: 190, pitch: 0 },
            },
            {
                id: 18,
                image: '/images360/sv-shub2.jpg',
                label: 'Student Hub',
                initialYaw: 180,
                forward: { yaw: 190, pitch: -2 },
                back: { yaw: 20, pitch: 0 },
            },
            {
                id: 19,
                image: '/images360/sv-shub3.jpg',
                label: 'Student Hub',
                initialYaw: 180,
                forward: { yaw: 160, pitch: -2 },
                back: { yaw: 0, pitch: 0 },
            },
            {
                id: 20,
                image: '/images360/sv-shub4.jpg',
                label: 'Go On',
                initialYaw: 180,
                forward: { yaw: 180, pitch: 0 },
                back: { yaw: 0, pitch: 0 },
            },
            {
                id: 21,
                image: '/images360/sv-shub5.jpg',
                label: 'Go On',
                initialYaw: 180,
                forward: { yaw: 180, pitch: 0 },
                back: { yaw: 0, pitch: 0 },
            },
            {
                id: 22,
                image: '/images360/sv_outside.jpg',
                label: 'You are arrive SV',
                initialYaw: 0,
            },
  ],
};

export const mphHQRoute: RouteDefinition = {
  id: 'mph-hq',
  title: 'MPH → HQ',
  fromNode: 'MPH',
  toNode: 'HQ',
  scenes: [
            {
                id: 1,
                image: '/images360/L-M-17.jpg',
                label: 'Multi Purpose Hall Lobby',
                initialYaw: 165,
                forward : { yaw: 165, pitch: -4 },
            },
            {
                id: 2,
                image: '/images360/L-M-16.jpg',
                label: 'Go out MPH Door',
                initialYaw: 90,
                back : { yaw: 360, pitch: 0 },
                forward: { yaw: 87, pitch: -5 },
            },
            {
                id: 3,
                image: '/images360/L-M-13.jpg',
                label: 'Go Straight',
                initialYaw: 180,
                back : { yaw: 360, pitch: 0 },
                forward: { yaw: 175, pitch: -5 },
            },
            {
                id: 4,
                image: '/images360/L-M-10.jpg',
                label: 'Go Straight',
                initialYaw: 180,
                back : { yaw: 353, pitch: 0 },
                forward: { yaw: 190, pitch: -4 },
            },
            {
                id: 5,
                image: '/images360/L-M-7.jpg',
                label: 'Enter Block A',
                initialYaw: 70,
                back : { yaw: 235, pitch: 0 },
                forward : { yaw: 90, pitch: 0 },
            },
            {
                id: 6,
                image: '/images360/lobby2.jpg',
                label: 'Enter the HQ 2nd Door',
                initialYaw: 270,
                forward: { yaw: 266, pitch: 0 },
                back: { yaw: 40, pitch: 0 },
            },
            {
                id: 7,
                image: '/images360/L-H-4.jpg',
                label: 'Student HQ Lobby',
                initialYaw: 340,
            },
  ],
};

export const mphDiningRoute: RouteDefinition = {
  id: 'mph-dining',
  title: 'MPH → Dining Hall',
  fromNode: 'MPH',
  toNode: 'Dining Hall',
  scenes: [
            {
                id: 1,
                image: '/images360/L-M-17.jpg',
                label: 'Multi Purpose Hall Lobby',
                initialYaw: 165,
                forward : { yaw: 165, pitch: -4 },
            },
            {
                id: 2,
                image: '/images360/L-M-16.jpg',
                label: 'Go out MPH Door',
                initialYaw: 90,
                back : { yaw: 360, pitch: 0 },
                forward: { yaw: 87, pitch: -5 },
            },
            {
                id: 3,
                image: '/images360/L-M-13.jpg',
                label: 'Go Straight',
                initialYaw: 180,
                back : { yaw: 360, pitch: 0 },
                forward: { yaw: 175, pitch: -5 },
            },
            {
                id: 4,
                image: '/images360/L-M-10.jpg',
                label: 'Go Straight',
                initialYaw: 180,
                back : { yaw: 353, pitch: 0 },
                forward: { yaw: 190, pitch: -4 },
            },
            {
                id: 5,
                image: '/images360/L-M-7.jpg',
                label: 'Enter Block A',
                initialYaw: 70,
                back : { yaw: 235, pitch: 0 },
                forward : { yaw: 90, pitch: 0 },
            },
            {
                id: 6,
                image: '/images360/LobbyA_1_Dining.jpg',
                label: 'A Block Lobby',
                initialYaw: 20,
                forward: { yaw: 0, pitch: 0 },
                back : { yaw: 235, pitch: 0 },
            },
            {
                id: 7,
                image: '/images360/LobbyA_3_Dining.jpg',
                label: 'Lobby A → G Block Corridor Entrance',
                initialYaw: 0,
                forward: { yaw: 0, pitch: 0 },
                back: { yaw: 200, pitch: -7 },
            },
            {
                id: 8,
                image: '/images360/LobbyA_5_Dining.jpg',
                label: 'Connecting Corridor',
                initialYaw: 0,
                forward: { yaw: 0, pitch: 0 },
                back: { yaw: 180, pitch: 0 },
            },
            {
                id: 9,
                image: '/images360/LobbyA_6_Dining.jpg',
                label: 'Corridor Midpoint',
                initialYaw: 190,
                forward: { yaw: 185, pitch: 0 },
                back: { yaw: 359, pitch: 0 },
            },
            {
                id: 10,
                image: '/images360/LobbyA_7_Dining.jpg',
                label: 'G Block Entrance Ahead',
                initialYaw: 220,
                forward: { yaw: 220, pitch: 0 },
                back: { yaw: 0, pitch: 0 },
            },
            {
                id: 11,
                image: '/images360/LobbyA_10_Dining.jpg',
                label: 'G Block Entrance Door',
                initialYaw: 0,
                forward: { yaw: 0, pitch: 0 },
                back: { yaw: 180, pitch: 0 },
            },
            {
                id: 12,
                image: '/images360/LobbyA_11_Dining.jpg',
                label: 'Inside G Block Lobby',
                initialYaw: 0,
                forward: { yaw: 0, pitch: -3 },
                back: { yaw: 180, pitch: -4 },
            },
            {
                id: 13,
                image: '/images360/LobbyA_12_Dining.jpg',
                label: 'Walkway Toward Dining Area',
                initialYaw: 0,
                forward: { yaw: 0, pitch: 0 },
                back: { yaw: 180, pitch: 0 },
            },
            {
                id: 14,
                image: '/images360/LobbyA_13_Dining.jpg',
                label: 'You are here, enjoy your meal!',
                initialYaw: 0,
            },
    ],
};

export const mphGblockRoute: RouteDefinition = {
  id: 'mph-gblock',
  title: 'MPH → G Block',
  fromNode: 'MPH',
  toNode: ' G Block',
  scenes: [
            {
                id: 1,
                image: '/images360/L-M-17.jpg',
                label: 'Multi Purpose Hall Lobby',
                initialYaw: 165,
                forward : { yaw: 165, pitch: -4 },
            },
            {
                id: 2,
                image: '/images360/L-M-16.jpg',
                label: 'Go out MPH Door',
                initialYaw: 90,
                back : { yaw: 360, pitch: 0 },
                forward: { yaw: 87, pitch: -5 },
            },
            {
                id: 3,
                image: '/images360/L-M-13.jpg',
                label: 'Go Straight',
                initialYaw: 180,
                back : { yaw: 360, pitch: 0 },
                forward: { yaw: 175, pitch: -5 },
            },
            {
                id: 4,
                image: '/images360/L-M-10.jpg',
                label: 'Go Straight',
                initialYaw: 180,
                back : { yaw: 353, pitch: 0 },
                forward: { yaw: 190, pitch: -4 },
            },
            {
                id: 5,
                image: '/images360/L-M-7.jpg',
                label: 'Enter Block A',
                initialYaw: 70,
                back : { yaw: 235, pitch: 0 },
                forward : { yaw: 90, pitch: 0 },
            },
            {
                id: 6,
                image: '/images360/LobbyA_1_Dining.jpg',
                label: 'A Block Lobby',
                initialYaw: 20,
                forward: { yaw: 0, pitch: 0 },
                back : { yaw: 235, pitch: 0 },
            },
            {
                id: 7,
                image: '/images360/LobbyA_3_Dining.jpg',
                label: 'Lobby A → G Block Corridor Entrance',
                initialYaw: 0,
                forward: { yaw: 0, pitch: 0 },
                back: { yaw: 200, pitch: -7 },
            },
            {
                id: 8,
                image: '/images360/LobbyA_5_Dining.jpg',
                label: 'Connecting Corridor',
                initialYaw: 0,
                forward: { yaw: 0, pitch: 0 },
                back: { yaw: 180, pitch: 0 },
            },
            {
                id: 9,
                image: '/images360/LobbyA_6_Dining.jpg',
                label: 'Corridor Midpoint',
                initialYaw: 190,
                forward: { yaw: 185, pitch: 0 },
                back: { yaw: 359, pitch: 0 },
            },
            {
                id: 10,
                image: '/images360/LobbyA_7_Dining.jpg',
                label: 'G Block Entrance Ahead',
                initialYaw: 220,
                forward: { yaw: 220, pitch: 0 },
                back: { yaw: 0, pitch: 0 },
            },
            {
                id: 11,
                image: '/images360/LobbyA_10_Dining.jpg',
                label: 'G Block Entrance Door',
                initialYaw: 0,
                forward: { yaw: 0, pitch: 0 },
                back: { yaw: 180, pitch: 0 },
            },
            {
                id: 12,
                image: '/images360/LobbyA_11_Dining.jpg',
                label: 'Inside G Block Lobby',
                initialYaw: 320,
            },
  ],
};

export const mphShubRoute: RouteDefinition = {
  id: 'mph-shub',
  title: 'MPH → Student Hub',
  fromNode: 'MPH',
  toNode: 'Student Hub',
  scenes: [
    {
                id: 1,
                image: '/images360/L-M-17.jpg',
                label: 'Multi Purpose Hall Lobby',
                initialYaw: 165,
                forward : { yaw: 165, pitch: -4 },
            },
            {
                id: 2,
                image: '/images360/L-M-16.jpg',
                label: 'Go out MPH Door',
                initialYaw: 90,
                back : { yaw: 360, pitch: 0 },
                forward: { yaw: 87, pitch: -5 },
            },
            {
                id: 3,
                image: '/images360/L-M-13.jpg',
                label: 'Go Straight',
                initialYaw: 180,
                back : { yaw: 360, pitch: 0 },
                forward: { yaw: 175, pitch: -5 },
            },
            {
                id: 4,
                image: '/images360/L-M-10.jpg',
                label: 'Go Straight',
                initialYaw: 180,
                back : { yaw: 353, pitch: 0 },
                forward: { yaw: 190, pitch: -4 },
            },
            {
                id: 5,
                image: '/images360/L-M-7.jpg',
                label: 'Enter Block A',
                initialYaw: 70,
                back : { yaw: 235, pitch: 0 },
                forward : { yaw: 90, pitch: 0 },
            },
            {
                id: 6,
                image: '/images360/LobbyA_1_Dining.jpg',
                label: 'A Block Lobby',
                initialYaw: 20,
                forward: { yaw: 0, pitch: 0 },
                back : { yaw: 235, pitch: 0 },
            },
            {
                id: 7,
                image: '/images360/LobbyA_3_Dining.jpg',
                label: 'Lobby A → G Block Corridor Entrance',
                initialYaw: 0,
                forward: { yaw: 0, pitch: 0 },
                back: { yaw: 200, pitch: -7 },
            },
            {
                id: 8,
                image: '/images360/LobbyA_5_Dining.jpg',
                label: 'Connecting Corridor',
                initialYaw: 0,
                forward: { yaw: 0, pitch: 0 },
                back: { yaw: 180, pitch: 0 },
            },
            {
                id: 9,
                image: '/images360/LobbyA_6_Dining.jpg',
                label: 'Corridor Midpoint',
                initialYaw: 190,
                forward: { yaw: 185, pitch: 0 },
                back: { yaw: 359, pitch: 0 },
            },
            {
                id: 10,
                image: '/images360/LobbyA_7_Dining.jpg',
                label: 'G Block Entrance Ahead',
                initialYaw: 220,
                forward: { yaw: 220, pitch: 0 },
                back: { yaw: 0, pitch: 0 },
            },
            {
                id: 11,
                image: '/images360/LobbyA_10_Dining.jpg',
                label: 'G Block Entrance Door',
                initialYaw: 0,
                forward: { yaw: 0, pitch: 0 },
                back: { yaw: 180, pitch: 0 },
            },
            {
                id: 12,
                image: '/images360/LobbyA_11_Dining.jpg',
                label: 'Inside G Block Lobby',
                initialYaw: 0,
                forward: { yaw: 0, pitch: -3 },
                back: { yaw: 180, pitch: -4 },
            },
            {
                id: 13,
                image: '/images360/LobbyA_12_Dining.jpg',
                label: 'Walkway Toward Dining Area',
                initialYaw: 0,
                forward: { yaw: 0, pitch: 0 },
                back: { yaw: 180, pitch: 0 },
            },
            {
                id: 14,
                image: '/images360/LobbyA_13_Dining.jpg',
                label: 'Dining Area First Section',
                initialYaw: 0,
                forward: { yaw: 0, pitch: -3 },
                back: { yaw: 180, pitch: 0 },
            },
            {
                id: 15,
                image: '/images360/LobbyA_17_Dining.jpg',
                label: 'Dining Area Mid Section',
                initialYaw: 0,
                forward: { yaw: 0, pitch: 0 },
                back: { yaw: 180, pitch: 0 },
            },
            {
                id: 16,
                image: '/images360/LobbyA_14_Dining.jpg',
                label: 'Dining Area',
                initialYaw: 0,
                forward: { yaw: 0, pitch: 0 },
                back: { yaw: 185, pitch: -7 },
            },
            {
                id: 17,
                image: '/images360/LobbyA_15_Dining.jpg',
                label: 'Student Hub Entrance Area',
                initialYaw: 15,
                forward: { yaw: 15, pitch: -3 },
                back: { yaw: 185, pitch: -7 },
            },
            {
                id: 18,
                image: '/images360/LobbyA_16_Dining.jpg',
                label: 'Inside Student Hub',
                initialYaw: 0,
                forward: { yaw: 0, pitch: -3 },
                back: { yaw: 176, pitch: -6 },
            },
            {
                id: 19,
                image: '/images360/StudentHub1.jpg',
                label: 'Inside Student Hub',
                initialYaw: 0,
            },
  ],
};

export const borneoRoutes = {
  'mph-library': mphLibraryRoute,
  'mph-junction': mphJunctionRoute,
  'mph-borneo': mphBorneoRoute,
  'mph-SV': mphSvRoute,
  'mph-hq': mphHQRoute,
  'mph-dining':mphDiningRoute,
  'mph-gblock': mphGblockRoute,
  'mph-shub': mphShubRoute,
};