import type { RouteDefinition } from './types';

export const shubMphRoute: RouteDefinition = {
  id: 'shub-mph',
  title: 'Student Hub → MPH',
  fromNode: 'Student Hub',
  toNode: 'MPH',
  scenes: [
            {
                id: 1,
                image: '/images360/StudentHub1.jpg',
                label: 'You arrive the Borneo Atrium! Welcome!',
                initialYaw: 180,
                forward: { yaw: 190, pitch: -7 },
            },
            {
                id: 2,
                image: '/images360/sv-shub1.jpg',
                label: 'Left side got escalator can go up to Junction',
                initialYaw: 275,
                back : { yaw: 10, pitch: 0 },
                forward : { yaw: 270, pitch: -5 },
            },
            {
                id: 2,
                image: '/images360/sv-shub2.jpg',
                label: 'Left side got escalator can go up to Junction',
                initialYaw: 190,
                back : { yaw: 10, pitch: 0 },
                forward : { yaw: 190, pitch: -5 },
            },
            {
                id: 2,
                image: '/images360/sv-shub3.jpg',
                label: 'Left side got escalator can go up to Junction',
                initialYaw: 175,
                back : { yaw: 10, pitch: 0 },
                forward : { yaw: 150, pitch: -5 },
            },
            {
                id: 2,
                image: '/images360/sv-shub4.jpg',
                label: 'Left side got escalator can go up to Junction',
                initialYaw: 120,
                back : { yaw: 300, pitch: 0 },
                forward : { yaw: 120, pitch: -5 },
            },
            {
                id: 2,
                image: '/images360/mph_exit_2.jpg',
                label: 'Left side got escalator can go up to Junction',
                initialYaw: 180,
                back : { yaw: 10, pitch: 0 },
                forward : { yaw: 180, pitch: -5 },
            },
            {
                id: 2,
                image: '/images360/mph_exit_1.jpg',
                label: 'Left side got escalator can go up to Junction',
                initialYaw: 200,
                back : { yaw: 10, pitch: 0 },
                forward : { yaw: 200, pitch: -5 },
            },
            {
                id: 2,
                image: '/images360/mph_exit_5.jpg',
                label: 'Left side got escalator can go up to Junction',
                initialYaw: 160,
                back : { yaw: 10, pitch: 0 },
                forward : { yaw: 160, pitch: -5 },
            },
            {
                id: 2,
                image: '/images360/mph_exit_4.jpg',
                label: 'Left side got escalator can go up to Junction',
                initialYaw: 270,
                back : { yaw: 90, pitch: 0 },
                forward : { yaw: 270, pitch: -5 },
            },
            {
                id: 4,
                image: '/images360/L-M-10.jpg',
                label: 'Go Straight',
                initialYaw: 0,
                forward: { yaw: 353, pitch: 0 },
                back: { yaw: 190, pitch: -4 },
              },
              {
                id: 5,
                image: '/images360/L-M-13.jpg',
                label: 'Ready to turn right into MPH',
                initialYaw: 360,
                forward: { yaw: 360, pitch: 0 },
                back: { yaw: 175, pitch: -5 },
              },
              {
                id: 6,
                image: '/images360/L-M-16.jpg',
                label: 'Enter the MPH Door',
                initialYaw: 360,
                forward: { yaw: 360, pitch: 0 },
                back: { yaw: 87, pitch: -5 },
              },
              {
                id: 7,
                image: '/images360/L-M-17.jpg',
                label: 'Multi Purpose Hall Lobby',
                initialYaw: 345,
                forward: { yaw: 340, pitch: 0 },
                back: { yaw: 165, pitch: -4 },
              },
              {
                id: 8,
                image: '/images360/L-M-18.jpg',
                label: 'You arrived at the MPH! Welcome!',
                initialYaw: 0,
                back: { yaw: 160, pitch: 0 },
              },
            
  ],
};

export const shubLibraryRoute: RouteDefinition = {
  id: 'shub-library',
  title: 'Student Hub → Library',
  fromNode: 'Student Hub',
  toNode: 'Library',
  scenes: [
            {
                id: 1,
                image: '/images360/StudentHub1.jpg',
                label: 'You are at Student Hub now. Leave here now.',
                initialYaw: 180,
                forward: { yaw: 190, pitch: -7 },
            },
            {
                id: 2,
                image: '/images360/LobbyA_15_Dining.jpg',
                label: 'Walk across the zebra line',
                initialYaw: 180,
                back : { yaw: 10, pitch: 0 },
                forward : { yaw: 180, pitch: -5 },
            },
            {
                id: 3,
                image: '/images360/LobbyA_14_Dining.jpg',
                label: 'Caution of the steps!',
                initialYaw: 190,
                back : { yaw: 10, pitch: 0 },
                forward : { yaw: 190, pitch: -5 },
            },
            
            {
              id: 4,
              image: "/images360/LobbyA_13_Dining.jpg",
              label: "Walk through the dining area",
              initialYaw: 180,
              forward: { yaw: 180, pitch: 0 },
            },
            {
              id: 5,
              image: "/images360/LobbyA_12_Dining.jpg",
              label: "Walk along the corridor",
              initialYaw: 180,
              forward: { yaw: 180, pitch: 0 },
            },
            {
              id: 6,
              image: "/images360/LobbyA_11_Dining.jpg",
              label: "You are at G block now. Keep going!",
              initialYaw: 180,
              forward: { yaw: 200, pitch: 0 },
            },
            {
              id: 7,
              image: "/images360/LobbyA_10_Dining.jpg",
              label: "Walk along the corridor",
              initialYaw: 220,
              forward: { yaw: 220, pitch: 0 },
            },
            {
              id: 8,
              image: "/images360/LobbyA_9_Dining.jpg",
              label: "Walk along the corridor",
              initialYaw: 180,
              forward: { yaw: 180, pitch: 0 },
            },
            {
              id: 9,
              image: "/images360/LobbyA_8_Dining.jpg",
              label: "Walk along the corridor",
              initialYaw: 180,
              forward: { yaw: 180, pitch: 0 },
            },
            {
              id: 10,
              image: "/images360/LobbyA_7_Dining.jpg",
              label: "Walk along the corridor",
              initialYaw: 0,
              forward: { yaw: 0, pitch: 0 },
            },
            {
              id: 11,
              image: "/images360/LobbyA_5_Dining.jpg",
              label: "Walk along the corridor",
              initialYaw: 180,
              forward: { yaw: 180, pitch: 0 },
            },
            {
              id: 12,
              image: "/images360/LobbyA_2_Dining.jpg",
              label: "You are at A block now!",
              initialYaw: 180,
              forward: { yaw: 180, pitch: 0 },
            },
            {
              id: 13,
              image: '/images360/lobby_c1.jpg',
              label: 'Block A Lobby',
              initialYaw: 180,
              forward: { yaw: 180, pitch: 0 },
              back: { yaw: 0, pitch: 0 },
            },
            {
              id: 14,
              image: '/images360/lobby_c4.jpg',
              label: 'Use Staircase to go Level 1 Library',
              initialYaw: 100,
              forward: { yaw: 110, pitch: 0 },
              back: { yaw: 330, pitch: 0 },
            },
            {
              id: 15,
              image: '/images360/library_c5.jpg',
              label: 'Go straight to Library Entrance',
              initialYaw: 360,
              forward: { yaw: 355, pitch: 0 },
              back: { yaw: 180, pitch: -30 },
            },
            {
              id: 16,
              image: '/images360/library_c7.jpg',
              label: 'Enter with using Student ID if got.',
              initialYaw: 360,
              forward: { yaw: 355, pitch: 0 },
              back: { yaw: 125, pitch: 0 },
            },
            {
              id: 17,
              image: '/images360/library12.jpg',
              label: 'Library Lobby',
              initialYaw: 30,
              forward: { yaw: 350, pitch: 0 },
              back: { yaw: 65, pitch: 0 },
            },
            {
              id: 18,
              image: '/images360/library_c9.jpg',
              label: 'Quiet Zone',
              initialYaw: 100,
              forward: { yaw: 180, pitch: 0 },
              back: { yaw: 270, pitch: 0 },
            },
            {
              id: 19,
              image: '/images360/library_c10.jpg',
              label: 'Book Section',
              initialYaw: 80,
              back: { yaw: 180, pitch: 0 },
            },
  ],
};

export const shubHQRoute: RouteDefinition = {
  id: 'shub-hq',
  title: 'Student Hub → HQ',
  fromNode: 'Student Hub',
  toNode: 'HQ',
  scenes: [
            {
                id: 1,
                image: '/images360/StudentHub1.jpg',
                label: 'You arrive the Borneo Atrium! Welcome!',
                initialYaw: 180,
                forward: { yaw: 190, pitch: -7 },
            },
            {
                id: 2,
                image: '/images360/LobbyA_15_Dining.jpg',
                label: 'Left side got escalator can go up to Junction',
                initialYaw: 180,
                back : { yaw: 10, pitch: 0 },
                forward : { yaw: 180, pitch: -5 },
            },
            {
                id: 3,
                image: '/images360/LobbyA_14_Dining.jpg',
                label: 'Left side got escalator can go up to Junction',
                initialYaw: 190,
                back : { yaw: 10, pitch: 0 },
                forward : { yaw: 190, pitch: -5 },
            },
            
            {
              id: 4,
              image: "/images360/LobbyA_13_Dining.jpg",
              label: "You are here • Library L1",
              initialYaw: 180,
              back : { yaw: 10, pitch: 0 },
              forward: { yaw: 180, pitch: 0 },
            },
            {
              id: 5,
              image: "/images360/LobbyA_12_Dining.jpg",
              label: "Walk along the corridor",
              initialYaw: 180,
              back : { yaw: 10, pitch: 0 },
              forward: { yaw: 180, pitch: 0 },
            },
            {
              id: 6,
              image: "/images360/LobbyA_11_Dining.jpg",
              label: "Stairs down near John's Pie",
              initialYaw: 180,
              back : { yaw: 10, pitch: 0 },
              forward: { yaw: 200, pitch: 0 },
            },
            {
              id: 7,
              image: "/images360/LobbyA_10_Dining.jpg",
              label: "Main Entrance — Block A",
              initialYaw: 220,
              back : { yaw: 10, pitch: 0 },
              forward: { yaw: 220, pitch: 0 },
            },
            {
              id: 8,
              image: "/images360/LobbyA_9_Dining.jpg",
              label: "Stairs down near John's Pie",
              initialYaw: 180,
              back : { yaw: 10, pitch: 0 },
              forward: { yaw: 180, pitch: 0 },
            },
            {
              id: 9,
              image: "/images360/LobbyA_8_Dining.jpg",
              label: "Stairs down near John's Pie",
              initialYaw: 180,
              back : { yaw: 10, pitch: 0 },
              forward: { yaw: 180, pitch: 0 },
            },
            {
              id: 10,
              image: "/images360/LobbyA_7_Dining.jpg",
              label: "Stairs down near John's Pie",
              initialYaw: 0,
              back : { yaw: 10, pitch: 0 },
              forward: { yaw: 0, pitch: 0 },
            },
            {
              id: 11,
              image: "/images360/LobbyA_5_Dining.jpg",
              label: "Stairs down near John's Pie",
              initialYaw: 180,
              back : { yaw: 10, pitch: 0 },
              forward: { yaw: 180, pitch: 0 },
            },
            {
              id: 12,
              image: "/images360/LobbyA_2_Dining.jpg",
              label: "Stairs down near John's Pie",
              initialYaw: 180,
              forward: { yaw: 180, pitch: 0 },
            },
            {
              id: 13,
              image: '/images360/lobby_c1.jpg',
              label: 'Block A Lobby',
              initialYaw: 230,
              forward: { yaw: 243, pitch: 0 },
            },
            {
              id: 14,
              image: '/images360/L-H-2.jpg',
              label: 'Student HQ Entrance',
              initialYaw: 0,
              forward: { yaw: 350, pitch: 0 },
              back: { yaw: 140, pitch: 0 },
            },
            {
              id: 15,
              image: '/images360/L-H-3.jpg',
              label: 'Financial Desk Services Area',
              initialYaw: 18,
              forward: { yaw: 55, pitch: 0 },
              back: { yaw: 160, pitch: 0 },
            },
            {
              id: 16,
              image: '/images360/L-H-4.jpg',
              label: 'Student HQ Lobby',
              initialYaw: 340,
              back: { yaw: 250, pitch: 0 },
            },
  ],
};

export const shubDiningRoute: RouteDefinition = {
  id: 'shub-dining',
  title: 'Student Hub → Dining Hall',
  fromNode: 'Student Hub',
  toNode: 'Dining Hall',
  scenes: [
            {
                id: 1,
                image: '/images360/StudentHub1.jpg',
                label: 'Leave Student hub',
                initialYaw: 180,
                forward: { yaw: 190, pitch: -7 },
            },
            {
                id: 2,
                image: '/images360/LobbyA_15_Dining.jpg',
                label: 'Go straight across the zebra line',
                initialYaw: 180,
                back : { yaw: 10, pitch: 0 },
                forward : { yaw: 180, pitch: -5 },
            },
            {
                id: 3,
                image: '/images360/LobbyA_14_Dining.jpg',
                label: 'Careful for the stairs',
                initialYaw: 190,
                back : { yaw: 10, pitch: 0 },
                forward : { yaw: 190, pitch: -5 },
            },
            
            {
                id: 4,
                image: "/images360/LobbyA_17_Dining.jpg",
                label: "You are here • Dining area",
                initialYaw: 180,
                back : { yaw: 10, pitch: 0 },
            },
  ],
};

export const shubBorneoRoute: RouteDefinition = {
  id: 'shub-borneo',
  title: 'Student Hub → Borneo Atrium',
  fromNode: 'Student Hub',
  toNode: 'Borneo Atrium',
  scenes: [
            {
                id: 1,
                image: '/images360/StudentHub1.jpg',
                label: 'You are at Student Hub now. Leave here now.',
                initialYaw: 180,
                forward: { yaw: 190, pitch: -7 },
            },
            {
                id: 2,
                image: '/images360/LobbyA_15_Dining.jpg',
                label: 'Walk across the zebra line',
                initialYaw: 180,
                back : { yaw: 10, pitch: 0 },
                forward : { yaw: 180, pitch: -5 },
            },
            {
                id: 3,
                image: '/images360/LobbyA_14_Dining.jpg',
                label: 'Caution of the steps!',
                initialYaw: 190,
                back : { yaw: 10, pitch: 0 },
                forward : { yaw: 190, pitch: -5 },
            },
            
            {
              id: 4,
              image: "/images360/LobbyA_13_Dining.jpg",
              label: "Walk through the dining area",
              initialYaw: 180,
              forward: { yaw: 180, pitch: 0 },
            },
            {
              id: 5,
              image: "/images360/LobbyA_12_Dining.jpg",
              label: "Walk along the corridor",
              initialYaw: 180,
              forward: { yaw: 180, pitch: 0 },
            },
            {
              id: 6,
              image: "/images360/LobbyA_11_Dining.jpg",
              label: "You are at G block now. Keep going!",
              initialYaw: 180,
              forward: { yaw: 200, pitch: 0 },
            },
            {
              id: 7,
              image: "/images360/LobbyA_10_Dining.jpg",
              label: "Walk along the corridor",
              initialYaw: 220,
              forward: { yaw: 220, pitch: 0 },
            },
            {
              id: 8,
              image: "/images360/LobbyA_9_Dining.jpg",
              label: "Walk along the corridor",
              initialYaw: 180,
              forward: { yaw: 180, pitch: 0 },
            },
            {
              id: 9,
              image: "/images360/LobbyA_8_Dining.jpg",
              label: "Walk along the corridor",
              initialYaw: 180,
              forward: { yaw: 180, pitch: 0 },
            },
            {
              id: 10,
              image: "/images360/LobbyA_7_Dining.jpg",
              label: "Walk along the corridor",
              initialYaw: 0,
              forward: { yaw: 0, pitch: 0 },
            },
            {
              id: 11,
              image: "/images360/LobbyA_5_Dining.jpg",
              label: "Walk along the corridor",
              initialYaw: 180,
              forward: { yaw: 180, pitch: 0 },
            },
            {
            id: 1,
            image: '/images360/L-B-1.jpg',
            label: 'Block A Lobby',
            initialYaw: 20,
            forward: { yaw: 30, pitch: 0 },
          },
          {
            id: 2,
            image: '/images360/L-B-3.jpg',
            label: 'Block A Groundfloor Toilet',
            initialYaw: 175,
            forward: { yaw: 178, pitch: -5 },
            back: { yaw: 70, pitch: -6 },
          },
          {
            id: 3,
            image: '/images360/L-B-6.jpg',
            label: 'Walkway in Corridor',
            initialYaw: 360,
            forward: { yaw: 355, pitch: 0 },
            back: { yaw: 89, pitch: -4 },
          },
          {
            id: 4,
            image: '/images360/L-B-8.jpg',
            label: 'Walkway in Corridor',
            initialYaw: 360,
            forward: { yaw: 355, pitch: 0 },
            back: { yaw: 175, pitch: -4 },
          },
          {
            id: 5,
            image: '/images360/L-B-10.jpg',
            label: 'Go Straight and ready turn left',
            initialYaw: 180,
            forward: { yaw: 165, pitch: -4 },
            back: { yaw: 358, pitch: 0 },
          },
          {
            id: 6,
            image: '/images360/L-B-12.jpg',
            label: 'Leisure Zone',
            initialYaw: 10,
            forward: { yaw: 355, pitch: 0 },
            back: { yaw: 250, pitch: -5 },
          },
          {
            id: 7,
            image: '/images360/L-B-15.jpg',
            label: 'You are almost there',
            initialYaw: 355,
            back: { yaw: 213, pitch: -6 },
          },
  ],
};

export const shubGblockRoute: RouteDefinition = {
  id: 'shub-gblock',
  title: 'Student Hub → G Block',
  fromNode: 'Student Hub',
  toNode: 'G Block',
  scenes: [
            {
                id: 1,
                image: '/images360/StudentHub1.jpg',
                label: 'You are at Student Hub now. Leave here now.',
                initialYaw: 180,
                forward: { yaw: 190, pitch: -7 },
            },
            {
                id: 2,
                image: '/images360/LobbyA_15_Dining.jpg',
                label: 'Walk across the zebra line',
                initialYaw: 180,
                back : { yaw: 10, pitch: 0 },
                forward : { yaw: 180, pitch: -5 },
            },
            {
                id: 3,
                image: '/images360/LobbyA_14_Dining.jpg',
                label: 'Caution of the steps!',
                initialYaw: 190,
                back : { yaw: 10, pitch: 0 },
                forward : { yaw: 190, pitch: -5 },
            },
            {
                id: 3,
                image: '/images360/LobbyA_17_Dining.jpg',
                label: 'Caution of the steps!',
                initialYaw: 190,
                back : { yaw: 10, pitch: 0 },
                forward : { yaw: 190, pitch: -5 },
            },
            
            {
              id: 4,
              image: "/images360/LobbyA_13_Dining.jpg",
              label: "Walk through the dining area",
              initialYaw: 180,
              forward: { yaw: 180, pitch: 0 },
            },
            {
              id: 5,
              image: "/images360/LobbyA_12_Dining.jpg",
              label: "Walk along the corridor",
              initialYaw: 180,
              forward: { yaw: 180, pitch: 0 },
            },
            {
              id: 6,
              image: "/images360/LobbyA_11_Dining.jpg",
              label: "You are at G block now. Keep going!",
              initialYaw: 180,
              forward: { yaw: 200, pitch: 0 },
            },
    ],
};

export const shubJunctionRoute: RouteDefinition = {
  id: 'shub-junction',
  title: 'Student Hub → Junction',
  fromNode: 'Student Hub',
  toNode: 'Junction',
  scenes: [
    {
                id: 1,
                image: '/images360/StudentHub1.jpg',
                label: 'You are at Student Hub now. Leave here now.',
                initialYaw: 180,
                forward: { yaw: 190, pitch: -7 },
            },
            {
                id: 2,
                image: '/images360/LobbyA_15_Dining.jpg',
                label: 'Walk across the zebra line',
                initialYaw: 180,
                back : { yaw: 10, pitch: 0 },
                forward : { yaw: 180, pitch: -5 },
            },
            {
                id: 3,
                image: '/images360/LobbyA_14_Dining.jpg',
                label: 'Caution of the steps!',
                initialYaw: 190,
                back : { yaw: 10, pitch: 0 },
                forward : { yaw: 190, pitch: -5 },
            },
            
            {
              id: 4,
              image: "/images360/LobbyA_13_Dining.jpg",
              label: "Walk through the dining area",
              initialYaw: 180,
              forward: { yaw: 180, pitch: 0 },
            },
            {
              id: 5,
              image: "/images360/LobbyA_12_Dining.jpg",
              label: "Walk along the corridor",
              initialYaw: 180,
              forward: { yaw: 180, pitch: 0 },
            },
            {
              id: 6,
              image: "/images360/LobbyA_11_Dining.jpg",
              label: "You are at G block now. Keep going!",
              initialYaw: 180,
              forward: { yaw: 200, pitch: 0 },
            },
            {
              id: 7,
              image: "/images360/LobbyA_10_Dining.jpg",
              label: "Walk along the corridor",
              initialYaw: 220,
              forward: { yaw: 220, pitch: 0 },
            },
            {
              id: 8,
              image: "/images360/LobbyA_9_Dining.jpg",
              label: "Walk along the corridor",
              initialYaw: 180,
              forward: { yaw: 180, pitch: 0 },
            },
            {
              id: 9,
              image: "/images360/LobbyA_8_Dining.jpg",
              label: "Walk along the corridor",
              initialYaw: 180,
              forward: { yaw: 180, pitch: 0 },
            },
            {
              id: 10,
              image: "/images360/LobbyA_7_Dining.jpg",
              label: "Walk along the corridor",
              initialYaw: 0,
              forward: { yaw: 0, pitch: 0 },
            },
            {
              id: 11,
              image: "/images360/LobbyA_5_Dining.jpg",
              label: "Walk along the corridor",
              initialYaw: 180,
              forward: { yaw: 180, pitch: 0 },
            },
            {
            id: 1,
            image: '/images360/L-B-1.jpg',
            label: 'Block A Lobby',
            initialYaw: 20,
            forward: { yaw: 30, pitch: 0 },
          },
          {
            id: 2,
            image: '/images360/L-B-3.jpg',
            label: 'Block A Groundfloor Toilet',
            initialYaw: 175,
            forward: { yaw: 178, pitch: -5 },
            back: { yaw: 70, pitch: -6 },
          },
          {
            id: 3,
            image: '/images360/L-B-6.jpg',
            label: 'Walkway in Corridor',
            initialYaw: 360,
            forward: { yaw: 355, pitch: 0 },
            back: { yaw: 89, pitch: -4 },
          },
          {
            id: 4,
            image: '/images360/L-B-8.jpg',
            label: 'Walkway in Corridor',
            initialYaw: 360,
            forward: { yaw: 355, pitch: 0 },
            back: { yaw: 175, pitch: -4 },
          },
          {
            id: 5,
            image: '/images360/L-B-10.jpg',
            label: 'Go Straight and ready turn left',
            initialYaw: 180,
            forward: { yaw: 165, pitch: -4 },
            back: { yaw: 358, pitch: 0 },
          },
          {
            id: 6,
            image: '/images360/L-B-12.jpg',
            label: 'Leisure Zone',
            initialYaw: 10,
            forward: { yaw: 355, pitch: 0 },
            back: { yaw: 250, pitch: -5 },
          },
          {
            id: 7,
            image: '/images360/L-B-15.jpg',
            label: 'You are almost there',
            initialYaw: 355,
            forward: { yaw: 355, pitch: -10 },
            back: { yaw: 213, pitch: -6 },
          },
          {
            id: 8,
            image: '/images360/L-J-16.jpg',
            label: 'Left side got escalator can go up to Junction',
            initialYaw: 325,
            forward: { yaw: 315, pitch: -10 },
            back: { yaw: 180, pitch: -6 },
          },
          {
            id: 9,
            image: '/images360/L-J-18.jpg',
            label: 'Go up escalator',
            initialYaw: 360,
            forward: { yaw: 360, pitch: 20 },
            back: { yaw: 290, pitch: -12 },
          },
          {
            id: 10,
            image: '/images360/L-J-19.jpg',
            label: 'Junction Balcony',
            initialYaw: 360,
            forward: { yaw: 10, pitch: -12 },
            back: { yaw: 175, pitch: -18 },
          },
          {
            id: 11,
            image: '/images360/L-J-20.jpg',
            label: 'You arrive Junction Level 1',
            initialYaw: 270,
            back: { yaw: 180, pitch: -4 },
          },
  ],
};

export const shubSvRoute: RouteDefinition = {
  id: 'shub-SV',
  title: 'Student Hub → Student Village',
  fromNode: 'Student Hub',
  toNode: 'Student Village',
  scenes: [
    {
                id: 1,
                image: '/images360/StudentHub1.jpg',
                label: 'You are at Student Hub now. Leave here now.',
                initialYaw: 180,
                forward: { yaw: 190, pitch: -7 },
            },
            {
                id: 2,
                image: '/images360/sv-shub1.jpg',
                label: 'Walk across the zebra line',
                initialYaw: 270,
                back : { yaw: 90, pitch: 0 },
                forward : { yaw: 270, pitch: -5 },
            },
            {
                id: 3,
                image: '/images360/sv-shub2.jpg',
                label: 'Caution of the steps!',
                initialYaw: 190,
                back : { yaw: 10, pitch: 0 },
                forward : { yaw: 190, pitch: -5 },
            },
            {
                id: 3,
                image: '/images360/sv-shub3.jpg',
                label: 'Caution of the steps!',
                initialYaw: 150,
                back : { yaw: 10, pitch: 0 },
                forward : { yaw: 150, pitch: -5 },
            },
            {
                id: 3,
                image: '/images360/sv-shub4.jpg',
                label: 'Caution of the steps!',
                initialYaw: 180,
                back : { yaw: 10, pitch: 0 },
                forward : { yaw: 180, pitch: -5 },
            },
            {
                id: 3,
                image: '/images360/sv-shub5.jpg',
                label: 'Caution of the steps!',
                initialYaw: 180,
                back : { yaw: 10, pitch: 0 },
                forward : { yaw: 180, pitch: -5 },
            },
            {
                id: 9,
                image: "/images360/mph_exit_7.jpg",
                label: "You are here",
                initialYaw: 90,
                back : { yaw: 180, pitch: 0 },
              },
  ],
};

export const borneoRoutes = {
    'shub-mph': shubMphRoute,
    'shub-library': shubLibraryRoute,
    'shub-hq': shubHQRoute,
    'shub-dining':shubDiningRoute,
    'shub-borneo': shubBorneoRoute,
    'shub-gblock': shubGblockRoute,
    'shub-junction': shubJunctionRoute,
    'shub-SV': shubSvRoute,
};
